- README.md
- docs/contribution.rst
- docs/index.rst
- docs/installation.rst
- docs/links.inc
This PR updates the `README.md` with badges and content and improves the content of `docs/`.
> docs: improve documentation

- docs/changes/latest.inc
- junifer/testing/datagrabbers.py
- junifer/testing/tests/test_spmauditory_datagrabber.py
* [*] fix #(52)
* [*] description of feature/fix
* [*] tests added/passed
* [*] add an entry to the [latest changes](../docs/changes/latest.inc)
> Implement #52 (SPM Auditory Testing Datagrabber)

- docs/changes/contributors.inc
- docs/changes/latest.inc
- junifer/datagrabber/datalad_base.py
This patch just adds a few comments to consider and changes the use of `datalad install` to `datalad clone`.
> Review DataladDataGrabber

- docs/changes/latest.inc
- examples/run_junifer_julearn.py
- pyproject.toml
Added an example of how to use junifer and julearn together to run feature extraction and machine learning on the Oasis dataset.
> docs: `junifer` +  `julearn` example

- junifer/api/__init__.py
- junifer/testing/registry.py
- junifer/testing/tests/test_testing_registry.py
- junifer/tests/test_main.py
> Fix issue #68

- junifer/data/__init__.py
coordinates stuff was not imported in the `__init__.py` file
> Fix imports

- conda-env.yml
- docs/changes/contributors.inc
- docs/changes/latest.inc
- junifer/datagrabber/aomic1000.py
- junifer/datagrabber/tests/test_aomic1000.py
- tools/create_aomic1000_example_dataset.py
Description of feature/fix:
Tests added/passed:
> Add data grabber for AOMIC1000 dataset

- docs/changes/latest.inc
- docs/conf.py
- junifer/markers/__init__.py
- junifer/markers/base.py
- junifer/markers/parcel.py
- junifer/markers/sphere_aggregation.py
- junifer/markers/sphere_aggregator.py
- junifer/markers/tests/test_parcel.py
- junifer/markers/tests/test_sphere_aggregation.py
> [ENH] Add support for a SphereAggregator marker

- docs/conf.py
- docs/sphinxext/gh_substitutions.py
- junifer/datagrabber/__init__.py
- junifer/markers/functional_connectivity_atlas.py
This PR lints, fixes imports and does general houskeeping of the codebase.
> chore: cleanup

- docs/changes/latest.inc
- junifer/datagrabber/base.py
- junifer/datagrabber/pattern.py
- junifer/datagrabber/tests/test_pattern_datalad.py
> Fix for #96

- junifer/configs/__init__.py
- junifer/configs/juseless/__init__.py
- junifer/configs/juseless/datagrabbers/__init__.py
- junifer/configs/juseless/datagrabbers/tests/test_ukb_vbm.py
- junifer/configs/juseless/datagrabbers/ukb_vbm.py
> Refactor juseless config module

- junifer/datareader/default.py
This PR completes the type annotations for `DefaultDataReader`.
> update: complete type annotations for DefaultDataReader

- docs/changes/latest.inc
> chore: fix latest.inc syntax

- docs/changes/latest.inc
- junifer/datagrabber/hcp.py
- junifer/datagrabber/pattern.py
- junifer/datagrabber/tests/test_hcp.py
- junifer/datagrabber/tests/test_pattern.py
- tools/create_hcp1200_example_dataset.py
This PR adds test for DataladHCP1200 datagrabber and thus also adds script for test dataset generation on Gin.
> update: add DataladHCP1200 datagrabber test

- .github/workflows/ci-docs.yml
- .github/workflows/ci.yml
- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/pypi.yml
- pyproject.toml
- tox.ini
Support Python 3.11
- Test Python 3.11
- Check `raise_error` implementation, as Python 3.11 has a new error reporting feature that is quite cool: https://docs.python.org/3/whatsnew/3.11.html
_No response_
_No response_
> [ENH]: Add support for python 3.11

- .github/workflows/ci-docs.yml
- docs/api/api.rst
- docs/api/configs.rst
- docs/api/data.rst
- docs/api/datagrabbers.rst
- docs/api/datareaders.rst
- docs/api/index.rst
- docs/api/markers.rst
- docs/api/pipeline.rst
- docs/api/preprocessing.rst
- docs/api/stats.rst
- docs/api/storage.rst
- docs/api/testing.rst
- docs/api/utils.rst
- docs/builtin.rst
- docs/contribution.rst
- docs/faq.rst
- docs/installation.rst
- docs/maintaining.rst
- docs/understanding/data.rst
- docs/understanding/datagrabber.rst
- docs/understanding/datareader.rst
- docs/understanding/marker.rst
- docs/understanding/preprocess.rst
- docs/understanding/storage.rst
This PR standardizes section and header ordering format for Sphinx docs.
> chore: standardize Sphinx section header ordering format

- docs/api/pipeline.rst
- junifer/api/decorators.py
- junifer/api/functions.py
- junifer/configs/juseless/datagrabbers/ixi_vbm.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/hcp.py
- junifer/markers/base.py
- junifer/markers/functional_connectivity_parcels.py
- junifer/markers/functional_connectivity_spheres.py
- junifer/markers/parcel_aggregation.py
- junifer/markers/sphere_aggregation.py
- junifer/preprocess/base.py
- junifer/preprocess/confounds/fmriprep_confound_remover.py
- junifer/stats.py
- junifer/storage/base.py
- junifer/storage/sqlite.py
- junifer/testing/datagrabbers.py
- junifer/utils/fs.py
- junifer/utils/logging.py
This PR improves rendering for certain portions of the docs.
> chore: improve docs rendering

- docs/builtin.rst
This PR cleans up the .rst tables for parcellations in `builtin.rst`.
> chore: parcellation table cleanup in docs

- tox.ini
> Update tox.ini for flake8 6.0.0

- .github/workflows/pypi.yml
- docs/maintaining.rst
- pyproject.toml
> Set up release system and start creating pre-releases

- .github/workflows/pypi.yml
- pyproject.toml
This PR updates the `pyproject.toml` and activates PyPI for releases.
> chore: update `pyproject.toml` and activate PyPI releases

- docs/changes/latest.inc
- junifer/api/functions.py
> A very powerfull double quote

- docs/builtin.rst
Like Parcellations (https://juaml.github.io/junifer/main/builtin.html) but for Coordinates
_No response_
> [DOC]: Fill in built-in coordinates list

- .github/workflows/ci-docs.yml
- .github/workflows/ci.yml
This PR makes AFNI available for CI.
> update: add AFNI to CI

- README.md
- docs/changes/0.0.1.inc
- docs/changes/latest.inc
- docs/index.rst
- docs/installation.rst
- docs/maintaining.rst
- docs/whats_new.rst
This PR improves docs and prepares for `v0.0.1`.
> release: 0.0.1

- docs/using/codeless.rst
- junifer/markers/falff/falff_base.py
- junifer/markers/falff/falff_estimator.py
- junifer/markers/falff/falff_parcels.py
- junifer/markers/falff/falff_spheres.py
- junifer/markers/falff/tests/test_falff_estimator.py
- junifer/markers/falff/tests/test_falff_parcels.py
- junifer/markers/falff/tests/test_falff_spheres.py
This PR fixes a typo in one of the docs' code blocks and lints the code base.
> docs: fix typo

- docs/changes/latest.inc
- junifer/data/parcellations.py
- junifer/datagrabber/pattern.py
- junifer/markers/parcel_aggregation.py
- junifer/markers/sphere_aggregation.py
- junifer/preprocess/confounds/fmriprep_confound_remover.py
This PR updates docstrings throughout the code base.
> chore: update docstrings

- docs/builtin.rst
- docs/changes/latest.inc
- junifer/data/VOIs/meta/Dosenbach2010_MNI_VOIs.txt
- junifer/data/coordinates.py
Would be great to have [Dosenbach coordinates](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_coords_dosenbach_2010.html?highlight=dosenbach#nilearn.datasets.fetch_coords_dosenbach_2010) in `junifer.data.coordinates`.
Like any other coordinates list.
_No response_
_No response_
> [ENH]: Add Dosenbach coordinates

- docs/changes/latest.inc
- junifer/datagrabber/aomic/id1000.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/aomic/tests/test_id1000.py
- junifer/datagrabber/aomic/tests/test_piop1.py
- junifer/datagrabber/aomic/tests/test_piop2.py
- tools/create_aomic1000_example_dataset.py
- tools/create_aomicpiop1_example_dataset.py
- tools/create_aomicpiop2_example_dataset.py
This pull request adds the fMRIprep masks for BOLD images in MNI space as well as T1w images in MNI space to the AOMIC datagrabbers.
> Add aomic masks

- docs/changes/latest.inc
- junifer/markers/falff/falff_base.py
- junifer/markers/falff/falff_parcels.py
- junifer/markers/falff/falff_spheres.py
- junifer/markers/reho/reho_parcels.py
- junifer/markers/reho/reho_spheres.py
> Add extra_input to reho/falff

- docs/changes/latest.inc
- junifer/api/functions.py
- junifer/api/res/run_conda.sh
- junifer/api/tests/test_functions.py
- junifer/markers/falff/falff_base.py
- junifer/markers/reho/reho_parcels.py
- junifer/markers/reho/reho_spheres.py
- junifer/preprocess/confounds/fmriprep_confound_remover.py
> Add support to source bash commands before run when queuing in htcondor

- docs/changes/latest.inc
- junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py
- junifer/markers/functional_connectivity/edge_functional_connectivity_parcels.py
- junifer/markers/functional_connectivity/edge_functional_connectivity_spheres.py
- junifer/markers/functional_connectivity/functional_connectivity_parcels.py
- junifer/markers/functional_connectivity/functional_connectivity_spheres.py
> Add missing extra_input parameters

- docs/changes/latest.inc
- junifer/markers/functional_connectivity/functional_connectivity_base.py
> add extra input parameter to abstract aggregate method in fc base

- docs/changes/latest.inc
- docs/conf.py
- pyproject.toml
This PR adds copy button in code blocks of the documentation.
> [ENH] Add copy button to documentation code blocks

- .github/workflows/docs.yml
- docs/conf.py
- pyproject.toml
Remove sphinx-multiversion from project dependencies and only add it to CI.
> Fix dependencies + CI

- docs/extending/coordinates.rst
- docs/extending/masks.rst
- docs/extending/parcellations.rst
Fix a few typos and copy paste errors from #203
> fix examples in adding coordinates and adding masks and few other typos

- README.md
- docs/changes/newsfragments/230.misc
- docs/contribution.rst
- docs/extending/datagrabber.rst
- docs/extending/marker.rst
- docs/help.rst
- docs/index.rst
- docs/installation.rst
- docs/maintaining.rst
- docs/understanding/pipeline.rst
- docs/understanding/preprocess.rst
- docs/using/queueing.rst
- docs/whats_new.rst
- ignore_words.txt
- pyproject.toml
- tox.ini
This PR improves `codespell` support by using `pyproject.toml` and fixing typos in docs.
> chore: improve `codespell` support

- docs/builtin.rst
- docs/changes/newsfragments/238.misc
- junifer/data/parcellations.py
- junifer/data/tests/test_parcellations.py
This PR improves docstrings and code style and parametrizes remaining tests for `junifer.data.parcellations`.
> chore: `junifer.data.parcellations` cleanup

- docs/Makefile
- docs/changes/newsfragments/242.doc
- docs/conf.py
- examples/run_junifer_julearn.py
- pyproject.toml
This PR bumps `julearn` version used in `examples` and also adapts the example to use new API.
> [MAINT]: bump and update `julearn` example

- docs/changes/newsfragments/132.change
- docs/changes/newsfragments/132.enh
- docs/changes/newsfragments/173.feature
- docs/changes/newsfragments/184.feature
- docs/changes/newsfragments/220.doc
- docs/changes/newsfragments/222.change
- docs/changes/newsfragments/222.enh
- docs/changes/newsfragments/223.bugfix
- docs/changes/newsfragments/223.enh
- docs/changes/newsfragments/225.feature
- docs/changes/newsfragments/226.enh
- docs/changes/newsfragments/227.enh
- docs/changes/newsfragments/228.misc
- docs/changes/newsfragments/229.misc
- docs/changes/newsfragments/230.misc
- docs/changes/newsfragments/232.misc
- docs/changes/newsfragments/234.enh
- docs/changes/newsfragments/235.bugfix
- docs/changes/newsfragments/236.change
- docs/changes/newsfragments/236.enh
- docs/changes/newsfragments/237.feature
- docs/changes/newsfragments/238.misc
- docs/changes/newsfragments/241.misc
- docs/changes/newsfragments/242.doc
- docs/whats_new.rst
This PR updates the `whats_new.rst` for 0.0.3 release.
> [MAINT]: Release 0.0.3

- README.md
- docs/changes/newsfragments/247.doc
- docs/contribution.rst
- docs/maintaining.rst
- junifer/data/masks.py
- junifer/data/tests/test_masks.py
- junifer/markers/tests/test_collection.py
- junifer/storage/pandas_base.py
- junifer/storage/tests/test_hdf5.py
- junifer/storage/tests/test_sqlite.py
This PR adds Zenodo shield in README and improves the docs.
> [DOC]: Add Zenodo shield and improve documentation

- docs/changes/newsfragments/258.enh
- junifer/pipeline/tests/test_workdir_manager.py
- junifer/pipeline/workdir_manager.py
This PR adds support for element-scoped directory and temporary directories to `WorkDirManager`.
> [ENH]: Add element-scoped directories for `WorkDirManager`

- docs/changes/newsfragments/262.misc
- docs/installation.rst
- junifer/api/cli.py
- junifer/api/res/fsl/applywarp
- junifer/api/res/fsl/flirt
- junifer/api/res/fsl/run_fsl_docker.sh
- junifer/api/res/fsl/std2imgcoord
- junifer/pipeline/utils.py
This PR adds support for accessing FSL via Docker wrapper similar to AFNI. Also adds a few FSL commands which will be used in junifer.
> [ENH]: Add support for FSL via Docker

- README.md
- docs/changes/newsfragments/269.misc
- docs/conf.py
- docs/extending/marker.rst
- docs/index.rst
- docs/installation.rst
- docs/understanding/preprocess.rst
- junifer/api/functions.py
- junifer/api/tests/test_functions.py
- junifer/data/tests/test_parcellations.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/base.py
- junifer/datagrabber/hcp1200/datalad_hcp1200.py
- junifer/datagrabber/hcp1200/hcp1200.py
- junifer/datagrabber/pattern.py
- junifer/datagrabber/tests/test_pattern.py
- junifer/datagrabber/utils.py
- junifer/markers/base.py
- junifer/markers/collection.py
- junifer/markers/falff/tests/test_falff_parcels.py
- junifer/markers/falff/tests/test_falff_spheres.py
- junifer/pipeline/update_meta_mixin.py
- junifer/storage/base.py
- junifer/utils/logging.py
- pyproject.toml
This PR improves documentation, packaging and general code style.
> [MAINT]: Improve docs, packaging and code style

- docs/changes/newsfragments/271.feature
- junifer/datagrabber/__init__.py
- junifer/datagrabber/dmcc13_benchmark.py
- junifer/datagrabber/tests/test_dmcc13_benchmark.py
- tools/create_dmcc13_benchmark_example_dataset.py
This PR adds DMCC13Benchmark DataGrabber based on the [DMCC13benchmark](https://openneuro.org/datasets/ds003452/versions/1.0.1) dataset. It is small enough for testing but feature-rich for analyses making it a good candidate for addition to junifer.
> [ENH]: Add DMCC13Benchmark DataGrabber

- docs/changes/newsfragments/277.misc
- docs/installation.rst
- junifer/api/cli.py
- junifer/api/res/ants/antsApplyTransforms
- junifer/api/res/ants/antsApplyTransformsToPoints
- junifer/api/res/ants/run_ants_docker.sh
- junifer/pipeline/utils.py
This PR adds support for accessing ANTs via Docker wrapper similar to AFNI and FSL. Also adds a few ANTs commands which will be used in junifer.
> [ENH]: Add support for ANTs via Docker

- docs/changes/newsfragments/279.misc
- junifer/api/res/afni/run_afni_docker.sh
- junifer/api/res/ants/run_ants_docker.sh
- junifer/api/res/fsl/run_fsl_docker.sh
This PR makes the external tool wrappers output to stderr instead of stdout to not pollute it.
> [ENH]: Use stderr for external tool wrappers' output

- docs/changes/contributors.inc
- docs/changes/newsfragments/291.doc
- docs/extending/masks.rst
> update: correct register_mask import in code example

- README.md
- docs/changes/newsfragments/294.misc
- pyproject.toml
This PR updates the pyproject.toml and adds FAIR shield in README.
> [MAINT]: Update README and pyproject.toml

- .github/dependabot.yml
- .github/workflows/ci.yml
- README.md
- docs/changes/newsfragments/300.doc
- docs/changes/newsfragments/300.enh
- docs/changes/newsfragments/300.misc
- docs/whats_new.rst
- junifer/api/tests/test_api_utils.py
- junifer/data/parcellations.py
- junifer/utils/logging.py
- pyproject.toml
This PR improves the repository with updated docs, code, code style and general CI stuff.
> [MAINT]: Improve repository

- docs/builtin.rst
- docs/changes/newsfragments/275.feature
- junifer/data/parcellations.py
- junifer/data/tests/test_parcellations.py
Request from @kaurao
Like other parcellations.
```shell
No.
```
_No response_
> [ENH]: Support Brainnetome 246 parcellation

- docs/builtin.rst
- docs/changes/newsfragments/317.doc
- docs/contribution.rst
- docs/extending/coordinates.rst
- docs/extending/datagrabber.rst
- docs/extending/dependencies.rst
- docs/extending/extension.rst
- docs/extending/index.rst
- docs/extending/marker.rst
- docs/extending/masks.rst
- docs/extending/parcellations.rst
- docs/extending/preprocessor.rst
- docs/installation.rst
- docs/links.inc
- docs/starting.rst
- docs/understanding/data.rst
- docs/understanding/datagrabber.rst
- docs/understanding/datareader.rst
- docs/understanding/index.rst
- docs/understanding/marker.rst
- docs/understanding/pipeline.rst
- docs/understanding/preprocess.rst
- docs/understanding/storage.rst
- docs/using/codeless.rst
- docs/using/index.rst
- docs/using/masks.rst
- docs/using/queueing.rst
This PR improves the documentation and in particular introduces space transformation via `SpaceWarper` and adds information about creating custom Preprocessors.
> [DOC]: Improve documentation

- docs/changes/newsfragments/325.change
- junifer/configs/juseless/datagrabbers/aomic_id1000_vbm.py
- junifer/configs/juseless/datagrabbers/camcan_vbm.py
- junifer/configs/juseless/datagrabbers/ixi_vbm.py
- junifer/configs/juseless/datagrabbers/ucla.py
- junifer/configs/juseless/datagrabbers/ukb_vbm.py
- junifer/data/tests/test_masks.py
- junifer/datagrabber/aomic/id1000.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/aomic/tests/test_id1000.py
- junifer/datagrabber/aomic/tests/test_piop1.py
- junifer/datagrabber/aomic/tests/test_piop2.py
- junifer/datagrabber/dmcc13_benchmark.py
- junifer/datagrabber/tests/test_dmcc13_benchmark.py
- junifer/preprocess/ants/tests/test_ants_apply_transforms_warper.py
- junifer/preprocess/tests/test_bold_warper.py
- junifer/preprocess/warping/tests/test_space_warper.py
> Follow the datasets BIDS convention for participants/sessions

- docs/changes/newsfragments/346.enh
- docs/changes/newsfragments/346.feature
- docs/understanding/data.rst
- junifer/datagrabber/aomic/id1000.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/aomic/tests/test_id1000.py
- junifer/datagrabber/aomic/tests/test_piop1.py
- junifer/datagrabber/aomic/tests/test_piop2.py
- junifer/datagrabber/utils.py
- junifer/datareader/default.py
- tools/create_aomic1000_example_dataset.py
- tools/create_aomicpiop1_example_dataset.py
- tools/create_aomicpiop2_example_dataset.py
This PR adds support for `FreeSurfer` data type patterns and adapts `DataladAOMICID1000`, `DataladAOMICPIOP1` and `DataladAOMICPIOP2` to it.
> [ENH]: Add support for `FreeSurfer` data type

- .gitmodules
- docs/changes/newsfragments/344.feature
- ignore_words.txt
- junifer/api/tests/test_api_utils.py
- junifer/data/tests/test_masks.py
- junifer/datagrabber/pattern.py
- junifer/markers/__init__.py
- junifer/markers/brainprint.py
- junifer/markers/reho/_afni_reho.py
- junifer/markers/reho/_junifer_reho.py
- junifer/markers/reho/reho_parcels.py
- junifer/markers/reho/reho_spheres.py
- junifer/markers/tests/test_brainprint.py
- pyproject.toml
- tox.ini
This PR adds support for `BrainPrint` marker.
> [ENH]: Add support for `BrainPrint`

- docs/changes/newsfragments/359.doc
- docs/using/running.rst
This PR adds documentation for analysing `storage`-like objects, for downstream analyses.
> [DOC]: Add doc for analysing `storage`-like objects

- .dockerignore
- .github/workflows/docker-docs-publish.yml
- Dockerfile-docs
- docs/changes/newsfragments/373.misc
This PR adds a Dockerfile for building docs and a gh-action workflow file for building and publishing the actual image.
> [CI]: Add Dockerfile for building docs

- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- docs/changes/newsfragments/374.misc
This PR adopts custom CI image for building junifer docs and docs preview.
> [CI]: Adopt custom CI image for junifer docs

- .github/workflows/docker-ci-publish.yml
- Dockerfile-ci
- docs/changes/newsfragments/382.misc
This PR adds a Dockerfile for CI and a gh-action workflow file for building and publishing the actual image.
> [CI]: Add Dockerfile for CI

- .github/workflows/docs.yml
- docs/changes/newsfragments/384.misc
This PR improves docs publishing action and adds a manual trigger for it.
> [MAINT]: Improve docs publishing

- .github/workflows/ci.yml
- docs/changes/newsfragments/383.misc
- tox.ini
This PR adopts custom CI image for testing junifer.
> [CI]: Adopt custom CI image for junifer test

- docs/changes/newsfragments/405.change
- docs/changes/newsfragments/405.enh
- junifer/datagrabber/aomic/id1000.py
- junifer/datagrabber/aomic/piop1.py
- junifer/datagrabber/aomic/piop2.py
- junifer/datagrabber/aomic/tests/test_id1000.py
- junifer/datagrabber/aomic/tests/test_piop1.py
- junifer/datagrabber/aomic/tests/test_piop2.py
- tools/create_aomic1000_example_dataset.py
- tools/create_aomicpiop1_example_dataset.py
- tools/create_aomicpiop2_example_dataset.py
> Provide data in all spaces for AOMIC datasets

- docs/changes/newsfragments/409.bugfix
- docs/changes/newsfragments/409.enh
- junifer/markers/falff/_afni_falff.py
- junifer/markers/falff/_junifer_falff.py
- junifer/markers/falff/falff_base.py
- junifer/markers/falff/tests/test_falff_spheres.py
- junifer/markers/reho/_afni_reho.py
- junifer/markers/reho/_junifer_reho.py
- junifer/markers/reho/reho_base.py
This PR updates the interface for AFNI-based markers and also fixes correct output suffices for AFNI outputs depending on NIfTI headers.
> [BUG]: Correct file reading for AFNI outputs

- docs/changes/newsfragments/413.change
- junifer/data/masks/_ants_mask_warper.py
- junifer/data/masks/_masks.py
- junifer/data/parcellations/_ants_parcellation_warper.py
- junifer/data/template_spaces.py
- junifer/data/tests/test_template_spaces.py
- junifer/preprocess/warping/_ants_warper.py
This PR replaces the `target_data` parameter of `get_template`, with `target_img`.
> [ENH]: Update `get_template` interface

- junifer/data/masks/_ants_mask_warper.py
- junifer/data/masks/_fsl_mask_warper.py
- junifer/data/masks/_masks.py
This PR adds a helper function for getting correct interpolation method for masks resampling via nilearn.
> [ENH]: Add helper function for getting correct interpolator for masks

- docs/changes/newsfragments/422.feature
- junifer/storage/base.py
- junifer/storage/hdf5.py
- junifer/storage/tests/test_hdf5.py
- junifer/storage/tests/test_storage_base.py
- junifer/storage/tests/test_utils.py
- junifer/storage/utils.py
> Allow to store 2d timeseries

- .github/workflows/ci.yml
- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- docs/changes/newsfragments/428.misc
> [CI]: Update CI workflows

- docs/changes/newsfragments/439.bugfix
- junifer/data/_dispatch.py
This PR corrects methods called for `*_data()` functions when dispatching.
> [BUG]: Correct methods for `*_data()` functions

- .github/workflows/ci.yml
- .github/workflows/docs-preview.yml
This PR adds block for cleaning up runner disk space.
> [CI]: Clean up runner
