docs/builtin.rst, docs/contribution.rst, docs/faq.rst
This PR updates the FAQs and available and planned pipeline steps and atlases.
=> Changes to documentation in FAQs and built-in components

junifer/markers/functional_connectivity_spheres.py, junifer/markers/tests/test_functional_connectivity_spheres.py
=> feat: add support for spheres-based functional connectivity

junifer/api/cli.py, junifer/api/tests/test_api_utils.py, junifer/api/tests/test_cli.py, junifer/api/utils.py
I've seen this in datalad and it's a very cool feature. When you run `datalad wtf`, you get a verbose print of all the characteristics of the runtime environment. Thus, whenever you submit an issue, you can copy/paste the output to help the developers understand what's going on.
As a new command in `junifer.api.cli` so we can run `junifer wtf`
```shell
No
```
We can check datalad, but beware of the license. Maybe we can also get an approval to copy/paste and release under AGPLv3.
=> [ENH]: Implement a command to print the running environment details

junifer/api/cli.py, junifer/api/tests/test_cli.py
It might be the case that some users have specific working environments that are not comprised within the tests from junifer (i.e. specific versions of the dependencies). For solving issues in a more efficient way, it might be good if we can have a `junifer selftest` command that run the test suite within the environment (so no `tox`, just `pytest`).
=> [ENH] Implement `junifer selftest` to allow the users to test the library themselves

docs/changes/latest.inc, examples/run_compute_parcel_mean.py, junifer/markers/__init__.py, junifer/markers/base.py, junifer/markers/ets_rss.py, junifer/markers/functional_connectivity_atlas.py, junifer/markers/functional_connectivity_spheres.py, junifer/markers/parcel_aggregation.py, junifer/markers/sphere_aggregation.py, junifer/markers/tests/test_functional_connectivity_atlas.py, junifer/markers/tests/test_markers_base.py, junifer/markers/tests/test_parcel.py, scratch/test_niftimasker.py
The idea is to have the `on` parameter of the markers to select the data types that the marker will be applied *on*, and use the `get_valid_inputs` function to verify that the marker is able to be computed on this kind of data.
=> [ENH] Refactor markers

docs/changes/latest.inc, junifer/__init__.py, junifer/external/__init__.py, junifer/external/nilearn/__init__.py, junifer/external/nilearn/junifer_nifti_spheres_masker.py, junifer/external/nilearn/tests/test_junifer_nifti_spheres_masker.py, junifer/markers/sphere_aggregation.py, junifer/markers/tests/test_sphere_aggregation.py
Requesting this as per:
```python3
if method != "mean":
raise_error(
"Only mean aggregation is supported for sphere aggregation. "
"If you need other aggregation methods, please open an issue "
"on `junifer github`_.",
NotImplementedError,
)
```
in https://github.com/juaml/junifer/blob/main/junifer/markers/sphere_aggregation.py.
I think it would be very useful if one can pass a function or name of function to the SphereAggregation Marker (other than 'mean').
This would be directly relevant for #36, as one could then simply define a kendalls_w function that can be passed as an aggregation method to SphereAggregation, which would give the reho value for that Sphere (if I understand this correctly).
I had a very quick look at nilearn and here is how they do it in a nutshell:
(from: …
=> [ENH]: Further Aggregation methods for SphereAggregation Marker

junifer/api/cli.py, tox.ini
```
(junifer)juseless ➜  junifer git:(feat/import) junifer run --help
Usage: junifer run [OPTIONS] FILEPATH
Run command for CLI.
Parameters ---------- filepath : click.Path     The filepath to the
configuration file. element : str     The element to operate using. verbose
: click.Choice     The verbosity level: warning, info or debug (default
"info").
Options:
--element TEXT
-v, --verbose [warning|info|debug]
--help                          Show this message and exit.
```
(junifer)juseless ➜  junifer git:(feat/import) junifer run --help
Usage: junifer run [OPTIONS] FILEPATH
Run junifer using the configuration from FILEPATH
Options:
--element TEXT
-v, --verbose [warning|info|debug]
--help                          Show this message and exit.
`junifer run --help`
```markdown
junifer: …
```
=> [BUG]: CLI help has the wrong format

junifer/api/functions.py, junifer/api/tests/test_functions.py
`julearn.api.functions.queue` and `julearn.api.functions._queue_condor` are currently not tested.
The functionality should be tested. At least that the YAML file is created, the submit file is somehow correct, the executable file is there, etc etc.
To consider:
- The logs directory should exist/be created. Otherwise the jobs will be on hold forever.
It will be ideal if we can check the validity of the submit file according to htcondor syntax.
=> [ENH] Include tests for the `queue` command

junifer/markers/ets_rss.py
This PR fixes the rendering in API docs for `RSSETSMarker`.
=> docs: fix RSSETSMarker rendering

docs/changes/latest.inc, junifer/data/parcellations.py, junifer/data/tests/test_parcellations.py, junifer/markers/ets_rss.py, junifer/markers/functional_connectivity_parcels.py, junifer/markers/parcel_aggregation.py, junifer/markers/tests/test_parcel_aggregation.py
It is common to compute markers on more than one parcel. However, some markers such as Functional Connectivity need to first extract signals from all the parcels and then compute the pairwise connectivity.
This could be done at the FC marker. However, it is also the case that there might be overlapping voxels (i.e. voxels that are present in both parcellations). 
Thus, the solution is to pass several parcellations to `ParcelAggregation`. This marker should first merge the parcells into one and then compute the aggregation.
However, in case of overlapping voxels, the order of the parcels should matter, as any voxel belonging to more than one parcellation should be placed in the parcellation that was first between the two.
Also, if the parcellations resolution do not match, it should be …
=> [ENH]: Allow ParcelAggregation to apply multiple parcellations at once

docs/changes/latest.inc, junifer/markers/utils.py
This PR introduces a singleton decorator in `junifer.markers.utils`, useful for markers using external toolboxes like `afni` to cache computations and other stuff.
=> update: add singleton decorator function for markers in `junifer.markers.utils`

docs/builtin.rst, docs/changes/latest.inc, docs/conf.py, junifer/api/res/afni/3dRSFC, junifer/markers/__init__.py, junifer/markers/falff/__init__.py, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_estimator.py, junifer/markers/falff/falff_parcels.py, junifer/markers/falff/falff_spheres.py, junifer/markers/falff/tests/test_falff_estimator.py, junifer/markers/falff/tests/test_falff_parcels.py, junifer/markers/falff/tests/test_falff_spheres.py
ALFF and fALFF
They can be calculated simultaneously as fALFF is just a scaling of ALFF in the full frequency range.
Inputs:
List of 3D MNI coordinates OR a mask file
Output:
Two arrays with one value per voxel, one for ALFF and one for fALFF
https://pubmed.ncbi.nlm.nih.gov/18501969/
_No response_
Equations here can be used:
https://web.conn-toolbox.org/fmri-methods/connectivity-measures/other#h.p_uBWGEgvizNhI
=> [MARKER]: (f)ALFF

docs/changes/latest.inc, junifer/testing/registry.py
This PR exposes `PartlyCloudyTestingDataGrabber` to `junifer.testing.registry`.
=> update: expose `PartlyCloudyTestingDataGrabber` to `testing.registry`

docs/changes/latest.inc, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_functions.py, junifer/markers/collection.py, junifer/markers/tests/test_collection.py
As of c6508a76, preprocess is not respected by `junifer run`.
Preprocess step should be executed.
As of c6508a76, `DataladAOMICPIOP1 > DefaultDataReader > fMRIPrepConfoundRemover > FunctionalConnectivityParcels`.
```markdown
junifer:
version: 0.0.1
python:
version: 3.11.0
dependencies:
click: 8.1.3
numpy: 1.23.4
datalad: 0.17.8
pandas: 1.4.4
nibabel: 4.0.2
nilearn: 0.9.2
sqlalchemy: 1.4.42
yaml: '6.0'
system:
platform: macOS-13.1-arm64-arm-64bit
environment:
LC_CTYPE: UTF-8
LC_TERMINAL: iTerm2
LC_TERMINAL_VERSION: 3.4.18
PATH: /Users/synchon/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/Users/synchon/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/synchon/opt/miniconda3/envs/juni …
```
=> [BUG]: Preprocess step is not respected by `junifer run`

docs/changes/latest.inc, junifer/configs/juseless/datagrabbers/ucla.py, junifer/datagrabber/aomic/id1000.py, junifer/datagrabber/aomic/piop1.py, junifer/datagrabber/aomic/piop2.py, junifer/datagrabber/pattern.py, junifer/datagrabber/tests/test_pattern.py
As of c6508a76, when loading the data for `BOLD_confounds` data type, the `PatternDataGrabber` (hence other dependent datagrabbers) does not add the `"format"` key to the `Junifer Data object`'s `BOLD_confounds` data type. This causes the `fMRIPrepConfoundRemover` to raise error later on when removing the confounds.
The `"format"` key should be available to the `BOLD_confounds` data type so that `fMRIPrepConfoundRemover` can pre-process normally.
As of c6508a76, `DataladAOMICPIOP1 > DefaultDataReader > fMRIPrepConfoundRemover > FunctionalConnectivityParcels`.
```markdown
junifer:
version: 0.0.1
python:
version: 3.11.0
dependencies:
click: 8.1.3
numpy: 1.23.4
datalad: 0.17.8
pandas: 1.4.4
nibabel: 4.0.2
nilearn: 0.9.2
sqlalchemy: 1.4.42
yaml: '6.0'
system:
platform: …
```
=> [BUG]: `PatternDataGrabber` does not respect the `"format"` parameter required for `BOLD_confounds` data type

docs/builtin.rst, docs/changes/latest.inc, junifer/data/__init__.py, junifer/data/masks.py, junifer/data/tests/test_masks.py, junifer/markers/ets_rss.py, junifer/markers/falff/falff_parcels.py, junifer/markers/falff/falff_spheres.py, junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py, junifer/markers/functional_connectivity/functional_connectivity_base.py, junifer/markers/functional_connectivity/functional_connectivity_parcels.py, junifer/markers/functional_connectivity/functional_connectivity_spheres.py, junifer/markers/parcel_aggregation.py, junifer/markers/reho/reho_parcels.py, junifer/markers/reho/reho_spheres.py, junifer/markers/sphere_aggregation.py, junifer/markers/tests/test_parcel_aggregation.py
Extracted from comment on #170 by @LeSasse:
> i would probably just take the literal name of the function and for now implement it with these three functions until there is demand for more:
>
> "compute_epi_mask" -> https://nilearn.github.io/dev/modules/generated/nilearn.masking.compute_epi_mask.html#nilearn.masking.compute_epi_mask
>
>"compute_brain_mask" -> https://nilearn.github.io/dev/modules/generated/nilearn.masking.compute_brain_mask.html#nilearn.masking.compute_brain_mask
>
>"compute_background_mask" -> https://nilearn.github.io/dev/modules/generated/nilearn.masking.compute_background_mask.html#nilearn.masking.compute_background_mask
>
>I think most of the parameters for the functions should be possible to use as well, the important ones are strings and numbers I think. In the …
=> [ENH]: Support for multiple computed masks

docs/changes/latest.inc, docs/understanding/storage.rst, junifer/data/masks.py, junifer/data/tests/test_masks.py, junifer/datagrabber/tests/test_hcp.py, junifer/markers/ets_rss.py, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_parcels.py, junifer/markers/falff/falff_spheres.py, junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py, junifer/markers/functional_connectivity/edge_functional_connectivity_parcels.py, junifer/markers/functional_connectivity/edge_functional_connectivity_spheres.py, junifer/markers/functional_connectivity/functional_connectivity_base.py, junifer/markers/parcel_aggregation.py, junifer/markers/reho/reho_base.py, junifer/markers/reho/reho_parcels.py, junifer/markers/reho/reho_spheres.py, junifer/markers/reho/tests/test_reho_parcels.py, junifer/markers/reho/tests/test_reho_spheres.py, junifer/markers/sphere_aggregation.py, junifer/markers/tests/test_collection.py, junifer/markers/tests/test_parcel_aggregation.py, junifer/markers/tests/test_sphere_aggregation.py, junifer/storage/base.py, junifer/storage/pandas_base.py, junifer/storage/sqlite.py, junifer/storage/tests/test_pandas_base.py, junifer/storage/tests/test_sqlite.py, junifer/storage/tests/test_storage_base.py, junifer/storage/utils.py
Currently we support:
1) Storing matrixes (named columns and rows, same dimensions for all elements)
2) Storing timeseries (named columns with variable number of rows, depending on the element)
3) Storing tables (same as timeseries, but the rows are not named "timepoint" but exposed to the user)
We are using "tables" to store "vectors". That is, 1 dimentional arrays. However, we have a whole logic set to allow for tables with different number of rows per element, as in timeseries. This does not make any sense. We should support:
1) matrixes
2) timeseries
3) vectors
1) rename "table" to vector and make them 1d arrays
2) remove `row_col_names` from `store_vector`
extra:
be consistent with `col_names` and `row_names`. Currently timeseries and vectors will have a `columns` parameter, while …
=> [ENH]: Rename 'table' to 'vector' in storage API

docs/api/index.rst, docs/api/nilearn.rst, docs/changes/latest.inc, junifer/external/nilearn/junifer_nifti_spheres_masker.py, junifer/external/nilearn/tests/test_junifer_nifti_spheres_masker.py, junifer/markers/falff/falff_spheres.py, junifer/markers/functional_connectivity/edge_functional_connectivity_spheres.py, junifer/markers/functional_connectivity/functional_connectivity_spheres.py, junifer/markers/reho/reho_spheres.py, junifer/markers/sphere_aggregation.py, junifer/markers/temporal_snr/temporal_snr_spheres.py, junifer/stats.py, junifer/tests/test_stats.py
Features:
* Allow for empty spheres (this will result in arrays with the second dimention of size 0). Applying any aggregation function should yield a NaN.
* Expose `allow_overlap` parameter to every sphere-based marker.
=> Add allow_overlap and allow empty spheres in sphere aggregation

.github/workflows/pypi.yml
This PR updates the `pypi.yml` to checkout git submodules and fix the build process.
=> fix: update `pypi.yml` to checkout git submodules

docs/changes/latest.inc, junifer/stats.py, junifer/tests/test_stats.py
Using the count aggregation function across one axis does not preserve the other dimensions.
The other dimensions should be respected
```python
import numpy as np
count(np.zeros((10, 0)), axis=-1)
```
This should give an array with 10 zeros.
Currently gives only a 0
```markdown
(junifer) inm7537 ➜  junifer git:(fix/empty_parcel) junifer wtf
junifer:
version: 0.0.1.dev75
python:
version: 3.11.0
dependencies:
click: 8.1.3
numpy: 1.23.4
datalad: 0.17.8
pandas: 1.5.1
nibabel: 4.0.2
nilearn: 0.9.2
sqlalchemy: 1.4.42
yaml: '6.0'
system:
platform: macOS-13.2.1-arm64-arm-64bit
environment:
LC_CTYPE: UTF-8
PATH: /Users/fraimondo/anaconda3/envs/junifer/bin:/Users/fraimondo/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/us …
```
=> [BUG]: The new "count" aggregation function does not respect multiple dimentions

docs/changes/latest.inc, junifer/markers/parcel_aggregation.py, junifer/markers/tests/test_parcel_aggregation.py
Currently, subjects in which a parcel has 0 voxels will result in different sized vectors/matrix/timeseries, which will later fail on collect.
As with spheres, we should allow for "empty" parcels and compute the corresponding NAN value.
=> [BUG]: allow for empty parcels in ParcelAggregation

docs/changes/latest.inc, junifer/storage/hdf5.py, junifer/storage/tests/test_hdf5.py
When using an HDF5FeatureStorage, the output log contains ERRORs related to HDF% storage.
```
2023-03-16 22:09:43,370 - JUNIFER - ERROR - HDF5 file not found at: /data/project/SPP2041/results/fraimondo/brain_size_project/storage/HCP_epi_mask_falff/element_100307_REST1_LR_HCP_epi_mask_falff.hdf5
2023-03-16 22:09:43,374 - JUNIFER - ERROR - `17194dc0bc12a30565cb1c46e04e2ea9` not found in: /data/project/SPP2041/results/fraimondo/brain_size_project/storage/HCP_epi_mask_falff/element_100307_REST1_LR_HCP_epi_mask_falff.hdf5
```
This is because the current implementation of H5io does not allow to test if a file contains certain variables. So all the "flow" of checking if the `meta` or certain md5 variable exists is done by try/catch blocks.
This is a not a good programming practice. For example, …
=> [BUG]: HDF5FeatureStorage raises errors under normal operation

pyproject.toml
Currently, docs are being built for all versions. This fix provides the right branch for sphinx_multiversion.
=> Use the right branch for sphinx_multiversion

docs/changes/newsfragments/215.bugfix, junifer/markers/ets_rss.py
This PR makes the `RSSETSMarker.compute()` output 2D instead of 1D.
=> [FIX]: Make timeseries output 2D for `RSSETSMarker`

docs/changes/newsfragments/214.enh, junifer/markers/base.py, junifer/preprocess/base.py
This PR adds missing `abstractmethod` decorators for `get_valid_inputs` methods of `BaseMarker` and `BasePreprocessor`.
=> [ENH]: Add missing decorators for `BaseMarker` and `BasePreprocessor`

docs/changes/newsfragments/185.bugfix, docs/changes/newsfragments/185.enh, docs/changes/newsfragments/201.enh, junifer/api/functions.py, junifer/api/tests/test_functions.py, junifer/datagrabber/datalad_base.py, junifer/datareader/default.py, junifer/datareader/tests/test_default_reader.py, junifer/markers/base.py, junifer/markers/tests/test_markers_base.py, junifer/pipeline/pipeline_step_mixin.py, junifer/pipeline/registry.py, junifer/pipeline/tests/test_pipeline_step_mixin.py, junifer/pipeline/tests/test_registry.py, junifer/preprocess/base.py, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/storage/hdf5.py
This PR addresses several issues:
The fmriPrepConfound remover and preprocessing in general do not have a good logging:
```
2023-03-14 21:52:18,428 - JUNIFER - INFO - Preprocessing data
2023-03-14 21:52:18,428 - JUNIFER - INFO - Computing BOLD
```
For example, it should say "Preprocessing BOLD"
And even in DEBUG mode, the messages are not verbose, so it might get stuck and we don't know where.
This is the current output:
```
2023-03-29 22:57:24,256 - JUNIFER - INFO - Parsing yaml file: /home/fraimondo/dev/projects/brain_size/1_compute_features/junifer_jobs/FCness_HCP_epi_brain_10mm/config.yaml
2023-03-29 22:57:24,260 - JUNIFER - INFO - Registering HCPCATConfounds in datagrabber
2023-03-29 22:57:24,260 - JUNIFER - INFO - Registering MultipleHCP in datagrabber
2023-03-29 22:57:24,261 - …
```
=> [ENH]: Several bug fixes

docs/builtin.rst, docs/changes/newsfragments/187.bugfix, docs/changes/newsfragments/216.change, docs/whats_new.rst, junifer/markers/__init__.py, junifer/markers/falff/__init__.py, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_estimator.py, junifer/markers/falff/falff_parcels.py, junifer/markers/falff/falff_spheres.py, junifer/markers/falff/tests/test_falff_estimator.py, junifer/markers/falff/tests/test_falff_parcels.py, junifer/markers/falff/tests/test_falff_spheres.py, junifer/markers/parcel_aggregation.py
This PR renames (f)ALFF markers to use shorter names and start with ALFF .i.e., `ALFFParcels` and `ALFFSpheres`.
=> [ENH]: Rename (f)ALFF markers to be shorter and ALFF prefixed

docs/changes/newsfragments/127.bugfix, junifer/api/parser.py, junifer/api/tests/test_parser.py
I use this yaml file:
```
workdir: /tmp
datagrabber:
kind: DataladAOMICPIOP1
tasks: "restingstate"
markers:
- name: Schaefer100x17_FC
kind: FunctionalConnectivityParcels
parcellation: Schaefer100x17
cor_method: correlation
storage: 
kind: SQLiteFeatureStorage
uri: ../storage/PIOP1
queue:
jobname: TestHTCondorQueue
kind: HTCondor
env:
kind: conda
name: junifer
mem: 8G
```
I would expect that the storage uri is interpreted relative from the directory where I run `junifer queue`, but it is interpreted relative to the cwd of the process.
I think it will be more intuitive to interpret relative from the directory where i run the `junifer queue`, i.e. my "perceived working directory".
Install junifer.
Use this yaml file and run `junifer queue`
```
workdir: /tmp
datagrabber:
kind: …
```
=> [BUG]: Storage URI in yaml config does not behave as I would expect.

docs/changes/newsfragments/183.bugfix, docs/changes/newsfragments/183.change, junifer/datagrabber/hcp.py, junifer/datagrabber/tests/test_hcp.py, tools/create_hcp1200_example_dataset.py
HCP1200 preprocessed BOLD data has the ICA+FIX preprocessed data. By default, we are providing this as BOLD. However, this is only present in the REST task, so it fails to find the files from other tasks.
This also means that the testing dataset in GIN is wrong.
The user should get the right files, even for NON REST tasks.
1. Use the HCP1200 datagrabber with a task to get bold data.
```markdown
junifer:
version: 0.0.2.dev78
python:
version: 3.11.0
dependencies:
click: 8.1.3
numpy: 1.23.4
datalad: 0.17.9
pandas: 1.5.1
nibabel: 4.0.2
nilearn: 0.9.2
sqlalchemy: 1.4.43
yaml: '6.0'
system:
platform: macOS-13.1-x86_64-i386-64bit
environment:
LC_CTYPE: UTF-8
PATH: /Users/fraimondo/Applications/workbench/bin_macosx64:/Users/fraimondo/.rbenv/shims:/Users/fraimondo/dev/tbox/f …
```
=> [BUG]: HCP1200 datagrabber does not provide the correct BOLD files

docs/changes/newsfragments/222.change, docs/changes/newsfragments/222.enh, docs/understanding/data.rst, docs/using/codeless.rst, docs/whats_new.rst, examples/run_ets_rss_marker.py, examples/run_junifer_julearn.py, examples/run_run_gmd_mean.py, examples/yamls/gmd_mean.yaml, examples/yamls/gmd_mean_htcondor.yaml, junifer/api/tests/data/gmd_mean.yaml, junifer/api/tests/data/gmd_mean_htcondor.yaml, junifer/api/tests/test_functions.py, junifer/data/tests/test_masks.py, junifer/markers/functional_connectivity/tests/test_crossparcellation_functional_connectivity.py, junifer/markers/reho/tests/test_reho_parcels.py, junifer/markers/reho/tests/test_reho_spheres.py, junifer/markers/tests/test_collection.py, junifer/markers/tests/test_ets_rss.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py, junifer/testing/datagrabbers.py, junifer/testing/registry.py, junifer/testing/tests/test_oasisvmbtesting_datagrabber.py, junifer/testing/tests/test_spmauditory_datagrabber.py, junifer/testing/tests/test_testing_registry.py
This PR renames the datagrabbers to `*DataGrabber` in `junifer.testing` to be consistent with the generally available ones in `junifer.datagrabber`.
=> [ENH]: Consistent `DataGrabber` naming in `testing`

README.md, docs/installation.rst
Make `junifer` available via `conda` by adding recipe to [conda-forge](https://conda-forge.org) channel. This will enable users to install `junifer` via:
```shell
conda install -c conda-forge junifer
```
=> Add `junifer` to `conda-forge`

docs/changes/newsfragments/228.misc, junifer/api/tests/test_functions.py, junifer/pipeline/tests/test_registry.py, junifer/utils/tests/test_logging.py
This PR makes the `pytest` fixtures used info, consistent in the docstrings.
=> chore: consistent pytest fixture naming

docs/changes/newsfragments/234.enh, junifer/markers/falff/falff_estimator.py, junifer/markers/reho/reho_estimator.py
This PR enables support for `stdout` and `stderr` capturing for `AFNI` commands run via `subprocess`, specifically for `ReHo` and `fALFF`. This should allow us to understand #233 better.
=> [ENH]: Enable `stdout` and `stderr` capturing for `AFNI` commands

docs/changes/newsfragments/235.bugfix, junifer/datagrabber/datalad_base.py
This is the standard error:
```
[INFO] Attempting a clone into /tmp/tmpmms6ilm3/datadir 
[INFO] Attempting to clone from https://github.com/datalad-datasets/human-connectome-project-openaccess.git to /tmp/tmpmms6ilm3/datadir 
[INFO] Attempting to clone from https://github.com/datalad-datasets/human-connectome-project-openaccess.git/.git to /tmp/tmpmms6ilm3/datadir 
[INFO] Completed clone attempts for Dataset(/tmp/tmpmms6ilm3/datadir) 
Traceback (most recent call last):
File "/home/fraimondo/miniconda3/envs/afni/bin/junifer", line 8, in <module>
sys.exit(cli())
File "/home/fraimondo/miniconda3/envs/afni/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/fraimondo/miniconda3/envs/afni/lib/python3.10/site-packages/click/core.py", …
```
=> [BUG]: No error is logged if datalad fails to clone a repository

docs/changes/newsfragments/236.change, docs/changes/newsfragments/236.enh, junifer/storage/base.py, junifer/storage/hdf5.py, junifer/storage/sqlite.py, junifer/storage/tests/test_hdf5.py, junifer/storage/tests/test_sqlite.py, junifer/storage/tests/test_storage_base.py
This PR adds a new `read()` method for `storage-like` objects. As of now, only `HDF5FeatureStorage` is implemented and allows to retrieve a feature as it is stored. This will allow users to do post-processing on the stored feature.
=> [ENH]: Add `read()` method for storage-like objects

docs/builtin.rst, docs/changes/newsfragments/173.feature, junifer/api/cli.py, junifer/data/parcellations.py, junifer/data/tests/test_parcellations.py
One parcellation that we like to use in a number of projects is the second version of the AICHA atlas (2021) because it is homotopic (find it here: https://www.gin.cnrs.fr/en/tools/aicha/). I checked with the parcellations that are planned as built in parcellations and it is not included there (https://juaml.github.io/junifer/main/builtin.html#id4). It might make sense to include it.
similar to other parcellations
_No response_
_No response_
=> [ENH]: Homotopic AICHA parcellation (version 2)

README.md, docs/api/index.rst, docs/api/onthefly.rst, docs/changes/newsfragments/237.feature, junifer/__init__.py, junifer/onthefly/__init__.py, junifer/onthefly/read_transform.py, junifer/onthefly/tests/test_read_transform.py, pyproject.toml, tox.ini
This PR introduces new `onthefly` sub-module for performing quick transformation of stored data, for further analyses. It intentionally doesn't store the transformed data back as it's cheap to compute and only required for downstream work. For now, it only has one function `read_transform()` to be used with other third-party libraries (`bctpy` for now). The docstring of `read_transform()` provides enough information on using it and also warnings on when it can cause issues. Unit tests are included as well.
=> [ENH]: Introduce new `onthefly` sub-module for quick transforms for analyses

docs/builtin.rst, docs/changes/newsfragments/225.feature, junifer/data/parcellations.py, junifer/data/tests/test_parcellations.py
There is now a homotopic version of the Schaefer Atlas (https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Yan2023_homotopic) which is going to be useful for many research questions especially targeted at lateralisation in the brain. The linked repo's readme also links to the corresponding publication.
As another in-built parcellation.
_No response_
_No response_
=> [ENH]: Homotopic Version of Schaefer Parcellation

docs/changes/newsfragments/241.misc, junifer/storage/tests/test_utils.py, pyproject.toml
This PR bumps `numpy` version constraints to make `junifer` compatible with `julearn`.
=> [MAINT]: Bump `numpy` version

docs/changes/newsfragments/132.change, docs/changes/newsfragments/132.enh, junifer/configs/juseless/datagrabbers/tests/test_ucla.py, junifer/configs/juseless/datagrabbers/ucla.py, junifer/datagrabber/aomic/id1000.py, junifer/datagrabber/aomic/piop1.py, junifer/datagrabber/aomic/piop2.py, junifer/datagrabber/aomic/tests/test_id1000.py, junifer/datagrabber/aomic/tests/test_piop1.py, junifer/datagrabber/aomic/tests/test_piop2.py, junifer/datagrabber/tests/test_datagrabber_utils.py, junifer/datagrabber/tests/test_pattern.py, junifer/datagrabber/utils.py
Datalad-based datasets such as DataladAOMICID1000, DataladAOMICPIOP1 and DataladAOMICPIOP2 have several data types including BOLD, T1w, DWI, etc.
So far, the types parameter is not exposed to the constructor, os a user that only requires one data type, will be forced to `datalad get` all the data.
easy, as with the `tasks` parameter, expose the `types` one.
_No response_
_No response_
=> [ENH]: Allow users to select `types` for datagrabbers in order to avoid downloading unnecesary data.

docs/changes/newsfragments/248.change, junifer/onthefly/read_transform.py
This PR adds `feature_md5` argument to `junifer.onthefly.read_transform()` to allow accessing storage features by MD5 hashes.
=> [ENH]: Add `feature_md5` argument to `read_transform()`

docs/builtin.rst, docs/changes/newsfragments/251.doc
[In this table](https://juaml.github.io/junifer/main/builtin.html#id6) the extended multiple-demand network is correctly listed as `extMDN`, but when using the following marker:
```
- name: extMDN
kind: SphereAggregation
coords: extMDN
radius: 5
method: mean
```
one gets the following error:
```
ValueError: Coordinates extMDN not found.
```
Using the `list_coordinates()` function, it seems clear why:
The naming is incorrect in junifer (`extDMN`)
```
>>> from junifer.data.coordinates import list_coordinates
>>> list_coordinates()
['CogAC', 'CogAR', 'DMNBuckner', 'Dosenbach', 'Empathy', 'Motor', 'MultiTask', 'PhysioStress', 'Power', 'Rew', 'Somatosensory', 'ToM', 'VigAtt', 'WM', 'eMDN', 'eSAD', 'extDMN']
```
It should have the correct name and the marker should work.
described above …
=> [BUG]: `extMDN` coordinates are falsely registered as `extDMN` coordinates in `junifer`

docs/changes/newsfragments/182.enh, docs/using/running.rst, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_cli.py, junifer/api/tests/test_functions.py, junifer/datagrabber/base.py, junifer/datagrabber/tests/test_base.py
I think in most data processing projects it is desirable to be able to select specific subsets of all subjects. Sometimes one just wants to get all available data, but sometimes one may want only specific subsets (like for example only unrelated subjects or subjects matched on some other variable). In other cases one may want to just preprocess a specific subset for some initial exploration or testing before getting the full sample. 
Add a subject parameter to in-built data grabbers. Ideally in the full pipeline one can add a list of subjects to the yaml directly, or for example by providing a "subject.txt" file that lists all desired subjects. Something like that.
_No response_
_No response_
=> [ENH]: Add support for subject(s) file for `junifer run`

docs/changes/newsfragments/259.enh, junifer/pipeline/tests/test_workdir_manager.py, junifer/pipeline/workdir_manager.py
This PR adds `cleanup_elementdir()` method to `WorkDirManager` to allow easy cleanup of element directory.
=> [ENH]: Improve element-specific directory cleanup for `WorkDirManager`

.github/workflows/lint.yml, .pre-commit-config.yaml, docs/changes/newsfragments/261.misc, tox.ini
This PR pins `ruff` to `0.1.0` as the lowest version to not break workflow and update `tox.ini`, `.pre-commit-config.yaml` and `lint.yml`.
=> [MAINT]: Pin `ruff` and update housekeeping configs

docs/changes/newsfragments/260.enh, junifer/preprocess/base.py, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py
This PR refactors internals of `BasePreprocessor` to make it easy for subclassing. It also adapts `fMRIPrepConfoundRemover` to base class changes.
=> [ENH]: Improve `BasePreprocessor` and `fMRIPrepConfoundRemover`

docs/changes/newsfragments/263.change, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_functions.py, junifer/markers/collection.py, junifer/markers/tests/test_collection.py
This PR refactors the pipeline internals to add support for multiple preprocessors.
=> [ENH]: Add support for multiple preprocessors in the pipeline

docs/changes/newsfragments/266.feature, junifer/preprocess/__init__.py, junifer/preprocess/fsl/__init__.py, junifer/preprocess/fsl/apply_warper.py, junifer/preprocess/fsl/tests/test_apply_warper.py
This PR introduces `_ApplyWarper` as a generic FSL `applywarp` wrapper class for internal use (as of now).
=> [ENH]: Introduce `_ApplyWarper`

docs/changes/newsfragments/267.feature, junifer/preprocess/__init__.py, junifer/preprocess/fsl/__init__.py, junifer/preprocess/fsl/bold_warper.py, junifer/preprocess/fsl/tests/test_bold_warper.py
This PR introduces `BOLDWarper` for warping BOLD data via FSL's `applywarp`.
=> [ENH]: Introduce `BOLDWarper`

docs/changes/newsfragments/274.bugfix, junifer/data/coordinates.py, junifer/data/masks.py, junifer/data/parcellations.py, junifer/preprocess/fsl/bold_warper.py
This PR makes native warped components (parcellations, coordinates and masks) persist after the warping is complete via element-scoped tempdirs and tempfiles. This is needed due to nibabel and numpy caching file paths for computation later.
=> [FIX]: Make native warped components persist

docs/changes/newsfragments/276.bugfix, junifer/data/masks.py, junifer/data/parcellations.py
This PR fixes the interpolation scheme for parcellation and mask transformation to native space, to nearest neighbour instead of spline.
=> [BUG]: Fix interpolation scheme for native parcellation and mask

docs/changes/newsfragments/278.bugfix, junifer/data/coordinates.py
This PR uses the recommended way to bypass the FSL `std2imgcoord` bug used in coordinates transformation to other template spaces.
=> [BUG]: Fix FSL `std2imgcoord` I/O

docs/changes/newsfragments/280.bugfix, junifer/data/coordinates.py
This PR adds `-std` to FSL `std2imgcoord` for coordinates warping to subject-native template space.
=> [BUG]: Fix FSL `std2imgcoord` source image

docs/changes/newsfragments/282.bugfix, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_estimator.py, junifer/markers/falff/tests/test_falff_estimator.py, junifer/markers/reho/reho_base.py, junifer/markers/reho/reho_estimator.py, junifer/markers/reho/reho_parcels.py, junifer/markers/reho/reho_spheres.py, junifer/markers/reho/tests/test_reho_estimator.py
This PR enables file path propagation for ReHo and fALFF maps from the estimator to the compute step so that aggregation markers can use it for conversion to other template spaces if and when required.
=> [BUG]: Propagate ReHo and fALFF maps' file paths

docs/changes/newsfragments/283.bugfix, junifer/pipeline/workdir_manager.py, junifer/storage/tests/test_utils.py
This fails:
```
WorkDirManager(
workdir="/home/fraimondo/dev/scratch/test_junifer_native/temp",
)
```
Because workdir is not a Path.
to work
1. Plain junifer from main
2. Just run this on ipython:
```
from junifer.pipeline import WorkDirManager
WorkDirManager(
workdir="/home/fraimondo/dev/scratch/test_junifer_native/temp", cleanup=False
)
```
```markdown
junifer:
version: 0.0.3.dev101
python:
version: 3.11.3
dependencies:
click: 8.0.4
numpy: 1.23.5
datalad: 0.18.2+59.gc5054cb91
pandas: 1.5.3
nibabel: 4.0.2
nilearn: 0.10.0
sqlalchemy: 1.4.48
ruamel.yaml: 0.17.31
system:
platform: Linux-6.1.0-12-amd64-x86_64-with-glibc2.36
environment:
LC_CTYPE: en_US.UTF-8
PATH: 
/home/fraimondo/miniconda3/envs/junifer/bin:/home/fraimondo/miniconda3/condabin:/home/fraimondo/.dotfiles …
```
=> [BUG]: WorkDirManager does not accept string as workdir

docs/changes/newsfragments/288.misc, junifer/preprocess/__init__.py, junifer/preprocess/bold_warper.py, junifer/preprocess/fsl/__init__.py, junifer/preprocess/fsl/apply_warper.py, junifer/preprocess/tests/test_bold_warper.py
This PR changes the location of `BOLDWarper` from `preprocess.fsl` sub-package to `preprocess` sub-package to make it tool-agnostic and enable support for warping via ANTs in the near future.
=> [MAINT]: Make `BOLDWarper` tool-agnostic

docs/changes/newsfragments/286.bugfix, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_estimator.py, junifer/markers/reho/reho_base.py, junifer/markers/reho/reho_estimator.py, junifer/markers/reho/reho_parcels.py, junifer/markers/reho/reho_spheres.py
This PR fixes the path propagation logic for `ReHoEstimator` and `ALFFEstimator` based on the input data space. If the input data space is "native", the original input data path is passed down for further use in `get_coordinates()` (as of now) for transforming coordinates to subject-"native" template space, else the actual ReHo and (f)ALFF map paths are passed down.
=> [BUG]: Correct path propagation logic for `ReHoEstimator` and `ALFFEstimator`

docs/changes/newsfragments/287.enh, junifer/api/tests/test_api_utils.py, junifer/stats.py, junifer/tests/test_stats.py, pyproject.toml
Add [mode](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html) as an aggregation function for `junifer.stats.get_aggfunc_by_name`.
Like any other aggregation function.
_No response_
_No response_
=> [ENH]: Add `mode` as an aggregation function for `get_aggfunc_by_name`

docs/changes/newsfragments/284.bugfix, junifer/data/masks.py, junifer/data/tests/test_masks.py, junifer/preprocess/confounds/fmriprep_confound_remover.py
I'm running a pipeline in which we use warp data to native space. The second preprocessing step is doing confound removal, while using a GM mask. The markers have `mask="inherit"`, so the same GM mask is used. What I see in the log is that the mask is warped twice, so in the end, it does not fit the subject's images and many voxels are not considered as part of the GM.
I expect the "inherited" mask not to be warped twice, since it's already warped in the preprocessing step.
1. Install junifer from main branch.
2. Run something like this:
```
workdir: /tmp
with:
- ../external/juni-farm/juni_farm/datagrabber/hcp_ya_confounds_cat.py
datagrabber:
kind: MultipleHCP
ica_fix: true
tasks:
- REST1
- REST2
preprocess:
- kind: BOLDWarper
reference: T1w
- kind: fMRIPrepConfoundRemover
detrend: true …
```
=> [BUG]: Mask "inherit" will be warped twice if working in native space.

docs/changes/newsfragments/295.feature, junifer/data/coordinates.py, junifer/data/masks.py, junifer/data/parcellations.py, junifer/markers/falff/falff_estimator.py, junifer/markers/reho/reho_estimator.py, junifer/preprocess/ants/ants_apply_transforms_warper.py, junifer/preprocess/fsl/apply_warper.py, junifer/utils/__init__.py, junifer/utils/helpers.py, junifer/utils/tests/test_helpers.py
This PR introduces a helper function `run_ext_cmd` to run external commands like those from FSL, ANTs and others.
=> [ENH]: Introduce `run_ext_cmd` for running external commands

.pre-commit-config.yaml, docs/api/data.rst, docs/changes/newsfragments/297.feature, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_api_utils.py, junifer/data/__init__.py, junifer/data/template_spaces.py, junifer/data/tests/test_data_utils.py, junifer/data/tests/test_masks.py, junifer/data/tests/test_template_spaces.py, junifer/data/utils.py, junifer/external/nilearn/junifer_nifti_spheres_masker.py, junifer/markers/falff/falff_base.py, junifer/markers/falff/falff_parcels.py, junifer/markers/falff/falff_spheres.py, junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py, junifer/markers/functional_connectivity/edge_functional_connectivity_parcels.py, junifer/markers/functional_connectivity/functional_connectivity_base.py, junifer/markers/reho/reho_estimator.py, junifer/markers/temporal_snr/temporal_snr_base.py, junifer/pipeline/tests/test_update_meta_mixin.py, junifer/storage/base.py, junifer/storage/hdf5.py, junifer/storage/sqlite.py, junifer/storage/tests/test_hdf5.py, junifer/storage/utils.py, junifer/testing/utils.py, pyproject.toml
This PR introduces a new function `junifer.data.get_xfm()` to fetch transformation files for moving between template spaces.
=> [ENH]: Introduce `get_xfm` for fetching transformation files

docs/changes/newsfragments/249.feature, docs/using/queueing.rst, junifer/api/functions.py, junifer/api/parser.py, junifer/api/res/run_conda.sh, junifer/api/res/run_venv.sh
Some people do not like to use conda, it would be nice to be able to set the `env` variable to a path of an environment created using [the venv tool](https://docs.python.org/3/library/venv.html) to run a junifer pipeline.
Similar to conda, but with venv.
_No response_
_No response_
=> [ENH]: Allow for using `venv` in queue kind

docs/changes/newsfragments/240.feature, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_cli.py, junifer/api/tests/test_functions.py, junifer/datagrabber/tests/test_dmcc13_benchmark.py, junifer/pipeline/registry.py
Sometimes I make a mistake with one parameter in the YAML. Then I need to go and check where the storage file points to, delete the directory and then finally run `junifer queue` with `--overwrite`.
I would like this process to be part of junifer.
`junifer reset /path/to/yaml`
This should delete the storage directory and the job directory.
Although the `reset` argument must not necessary be that one.
_No response_
_No response_
=> [ENH]: Implement `junifer reset` to delete job/results file.

docs/changes/newsfragments/310.change, docs/changes/newsfragments/310.enh, junifer/preprocess/base.py, junifer/preprocess/bold_warper.py, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py, junifer/preprocess/tests/test_bold_warper.py, junifer/preprocess/tests/test_preprocess_base.py
This PR refactors `preprocess` method of preprocessors to not return "data type" and only return the preprocessed input data. Having to return "data type" forced a concrete preprocessor to only operate on a single "data type" (like `BOLDWarper` introduced in #267) and not allow the `on` parameter to be exposed to the user (as requested in #301). If a concrete preprocessor adds new "data type" like `BOLD_mask` in the "junifer data object" as `fMRIPrepConfoundRemover` (introduced in #111) does, it will be handled as usual with no changes.
A preprocessor should not create new "data types" (which was allowed earlier and hence the restriction) but only create and add "helper data types" like `BOLD_mask` which happens via `extra_input` of the `preprocess` method.
=> [ENH]: Improve `BasePreprocessor`

.github/workflows/ci-docs.yml, .github/workflows/ci.yml, .github/workflows/docs-preview.yml, .github/workflows/docs.yml, .github/workflows/pypi.yml, docs/changes/newsfragments/270.misc, junifer/api/tests/test_api_utils.py, junifer/utils/logging.py, pyproject.toml, tox.ini
This PR adds support for Python 3.12 by adding tests against it in CI and makes Python 3.11 the base for coverage and CI checks.
=> [MAINT]: Add support for Python 3.12

docs/changes/newsfragments/312.bugfix, junifer/api/queue_context/htcondor_adapter.py, junifer/api/queue_context/tests/test_htcondor_adapter.py
This PR fixes the script generation of `HTCondorAdapter` to allow proper parsing of HTCondor's `VARS`. In particular, replaces single quote with double quotes for element parsing.
=> [FIX]: Element parsing for HTCondor via `VARS`

docs/changes/newsfragments/314.bugfix, junifer/datagrabber/dmcc13_benchmark.py
This PR fixes uncaught bugs for correct access of all elements using the `DMCC13Benchmark` DataGrabber.
=> [FIX]: Element access for `DMCC13Benchmark`

docs/changes/newsfragments/324.bugfix, junifer/markers/parcel_aggregation.py
When I apply a mask in FC extraction using a YAML pipeline it fails.
I would like it to apply the mask correctly and not fail.
1. See environment below.
2. See the Yaml here:
```
workdir: /tmp
datagrabber:
kind: DataladAOMICID1000
preprocess:
kind: Smoothing
using: "nilearn"
"on": "BOLD"
smoothing_params:
fwhm: 10
storage:
kind: HDF5FeatureStorage
uri: data/aomic_id1000.hdf5
markers:
- name: parccortical-Schaefer100x17FSLMNI_marker-empiricalFC
kind: FunctionalConnectivityParcels
parcellation: Schaefer100x17
cor_method: correlation
cor_method_params:
empirical: true
masks:
- inherit
queue:
jobname: smoothing_test
kind: HTCondor
collect: on_success_only
env:
kind: venv
name: env
mem: 20G
verbose: 8
pre_run: |
source /data/group/appliedml/tools/ants_2.5.0/ants.sh
```
```markdown
❱ junifer …
```
=> [BUG]: Extra dimension added to parcellation after warping to another template space via ANTs

docs/changes/newsfragments/323.feature, junifer/api/cli.py, junifer/api/functions.py, junifer/api/tests/test_cli.py, junifer/api/tests/test_functions.py
I think it would be fantastic if junifer had a `list-elements` command line function which can be run on a yaml file with a specific datagrabber, and that will then print out all available elements in the format that junifer likes for subsetting the element keys using the `--element elements.txt` command line option for queue.
The workflow i imagine would have the advantage that i can very easily discover elements and subset them for testing using arbitrary command line filters, and then write them into a file for queing i.e.:
`junifer list-elements <yaml> | tail -2 > elements.txt`
as above
_No response_
_No response_
=> [ENH]: Add `junifer list-elements` for listing out elements of an YAML's  DataGrabber

docs/api/nilearn.rst, docs/api/onthefly.rst, docs/changes/newsfragments/115.doc, junifer/api/__init__.py, junifer/api/queue_context/__init__.py, junifer/configs/__init__.py, junifer/configs/juseless/__init__.py, junifer/configs/juseless/datagrabbers/__init__.py, junifer/data/__init__.py, junifer/data/coordinates.py, junifer/data/masks.py, junifer/data/parcellations.py, junifer/data/template_spaces.py, junifer/datagrabber/__init__.py, junifer/datareader/__init__.py, junifer/external/__init__.py, junifer/external/nilearn/__init__.py, junifer/markers/__init__.py, junifer/onthefly/__init__.py, junifer/pipeline/__init__.py, junifer/preprocess/__init__.py, junifer/stats.py, junifer/storage/__init__.py, junifer/testing/__init__.py, junifer/testing/datagrabbers.py, junifer/utils/__init__.py
Every `__init__.py` file needs to document the purpose of the package, so it does not render like this in the API doc:
_No response_
=> [DOC]: Change `__init__.py` docstrings to reflect sub-packages

docs/changes/newsfragments/330.doc, junifer/datagrabber/aomic/id1000.py, junifer/datagrabber/aomic/piop1.py, junifer/datagrabber/aomic/piop2.py, junifer/datagrabber/dmcc13_benchmark.py
https://github.com/juaml/junifer/blob/08ac0d9872664f39ae75537c0c4636accc33ef79/junifer/datagrabber/aomic/id1000.py#L27-L28
vs
https://github.com/juaml/junifer/blob/08ac0d9872664f39ae75537c0c4636accc33ef79/junifer/datagrabber/aomic/id1000.py#L53-L70
_No response_
=> [DOC]: Add missing types in DataGrabber `types` docstrings

docs/changes/newsfragments/332.bugfix, junifer/api/functions.py
1. Queue a job (do not submit)
2. Run junifer reset
You see this:
```
OSError: [Errno 39] Directory not empty: '/home/fraimondo/dev/scratch/neurodc/junifer_jobs'
```
No error, and that directory is not deleted.
1. Install latest (--pre) from pip
2. Queue any yaml
```markdown
junifer:
version: 0.0.5.dev27
python:
version: 3.11.8
dependencies:
click: 8.1.7
numpy: 1.26.4
scipy: 1.11.4
datalad: 0.19.6
pandas: 2.1.4
nibabel: 5.2.1
nilearn: 0.10.2
sqlalchemy: 2.0.29
ruamel.yaml: 0.17.40
httpx: 0.26.0
tqdm: 4.66.1
templateflow: 24.2.0
looseversion: None
system:
platform: Linux-6.6.13+bpo-amd64-x86_64-with-glibc2.36
environment:
LC_CTYPE: en_US.UTF-8
PATH: 
/home/fraimondo/miniconda3/envs/neurodc/bin:/home/fraimondo/miniconda3/condabin:/home/fraimondo/.dotfiles/bin:/usr/loc …
```
=> [BUG]: `junifer reset` fails as it tries to delete `junifer_jobs` directory

docs/changes/newsfragments/340.bugfix, junifer/markers/parcel_aggregation.py
This PR fixes extra dimension addition to mask after warping via ANTs.
=> [BUG]: Extra dimension added to mask after warping via ANTs

docs/changes/newsfragments/339.bugfix, junifer/markers/collection.py
I'm running a YAML with two pre-processing steps: confound remover + Space Warper.
The process fails because the Space Warper requires the T1w + Warp which is not outputed by the fMRIPrepConfoundRemover. 
The bug is basically that: it's not accounting that the data object has the T1w and Warp objects. It just gets the output of the fMRIPrepConfoundRemover.
I would expect that the two steps can be used.
1. Install latest junifer
2. Run: `junifer run --element sub-0001 NAME_OF_YAML`
```yaml
workdir: /tmp
datagrabber:
kind: DataladAOMICID1000
native_t1w: true
preprocess:
- kind: fMRIPrepConfoundRemover
detrend: true
standardize: true
strategy:
motion: full
wm_csf: full
global_signal: full
low_pass: 0.08
high_pass: 0.01
masks:
- inherit
- compute_epi_mask
- threshold: 0
- kind: SpaceWarper …
```
=> [BUG]: Validation failure of multiple pre-processing steps with different input data types requirement

docs/changes/newsfragments/342.misc, docs/installation.rst, junifer/api/cli.py, junifer/api/res/freesurfer/mri_binarize, junifer/api/res/freesurfer/mri_mc, junifer/api/res/freesurfer/mri_pretess, junifer/api/res/freesurfer/mris_convert, junifer/api/res/freesurfer/run_freesurfer_docker.sh, junifer/pipeline/utils.py
This PR adds support for accessing FreeSurfer via Docker wrapper similar to AFNI, FSL and ANTs. Also adds a few FreeSurfer commands which will be used in junifer.
=> [ENH]: Add support for FreeSurfer via Docker

docs/changes/newsfragments/341.enh, docs/extending/datagrabber.rst, docs/extending/marker.rst, docs/understanding/data.rst, docs/understanding/preprocess.rst, junifer/api/functions.py, junifer/configs/juseless/datagrabbers/tests/test_ucla.py, junifer/configs/juseless/datagrabbers/ucla.py, junifer/data/masks.py, junifer/data/parcellations.py, junifer/data/tests/test_masks.py, junifer/datagrabber/aomic/id1000.py, junifer/datagrabber/aomic/piop1.py, junifer/datagrabber/aomic/piop2.py, junifer/datagrabber/aomic/tests/test_id1000.py, junifer/datagrabber/aomic/tests/test_piop1.py, junifer/datagrabber/aomic/tests/test_piop2.py, junifer/datagrabber/datalad_base.py, junifer/datagrabber/dmcc13_benchmark.py, junifer/datagrabber/pattern.py, junifer/datagrabber/pattern_datalad.py, junifer/datagrabber/tests/test_datagrabber_utils.py, junifer/datagrabber/tests/test_dmcc13_benchmark.py, junifer/datagrabber/utils.py, junifer/datareader/default.py, junifer/preprocess/base.py, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py, junifer/testing/datagrabbers.py, junifer/testing/tests/test_partlycloudytesting_datagrabber.py
This PR refactors the `patterns` for DataGrabbers by introducing "nested data types" like `mask` for particular data type like `BOLD` instead of `BOLD_mask`. This cleans up the interface and logically groups the available data while reducing the chances of silly errors like not specifying `BOLD_mask` in DataGrabber `types` when mask is desired from the dataset.
=> [ENH]: Refactor DataGrabber `patterns`

docs/changes/newsfragments/343.feature, docs/understanding/storage.rst, junifer/storage/base.py, junifer/storage/hdf5.py, junifer/storage/tests/test_hdf5.py
This PR introduces a new storage type called `scalar_table` which is basically a table with scalar values. The data type is like a mix between `matrix` with user-defined `row_names` and `row_header_col_name` and `timeseries` like internal data storage i.e., non-uniform row and column count but fixed row count across elements. For now, storing `eigenvalues` from `BrainPrint` (#344)  would use this and is only supported by `HDF5FeatureStorage`.
=> [ENH]: Add scalar table storage support for `HDF5FeatureStorage`

docs/changes/newsfragments/345.feature, docs/extending/datagrabber.rst, junifer/datagrabber/pattern.py, junifer/datagrabber/tests/test_pattern.py
This PR adds support for specifying Unix path expansion directives like `[], [!]` for `PatternDataGrabber` patterns. This is an improvement which is needed for supporting `FreeSurfer` data type. For example, `fsaverage` directory is at the same level as subjects like `sub-0001` for AOMIC datasets and `[!f]` allows to not glob the `fsaverage` directory without overriding `get_elements()` method. As the `.mgz` and other outputs of `FreeSurfer` are not unique by subject (and/or task / session) prefix, globbing doesn't work as usual (at least for the AOMIC datasets). This also enables one to have the pattern: `.../T1.mg[z]` to make it work.
=> [ENH]: Unix path expansion directives support for `PatternDataGrabber`

docs/changes/newsfragments/136.enh, junifer/external/nilearn/__init__.py, junifer/external/nilearn/junifer_nifti_spheres_masker.py, junifer/external/nilearn/tests/test_junifer_nifti_spheres_masker.py
We reimplemented (by copying) a `JuniferNiftiSpheresMasker` that has the same functionality of `NiftiSpheresMasker` but allows to change the aggregation function.
The tests are also a copy of Nilearn's one.
If `agg_function = 'mean'`, then they should both behave equally. I would like to have a test so we can corroborate this. They should be numerically equal.
One more test in `junifer.external.nilearn.tests`
_No response_
_No response_
=> [ENH]: Add test for `JuniferNiftiSpheresMasker` against nilearn's version

docs/changes/newsfragments/327.doc, docs/using/queueing.rst
would be good to add an example for venv here as well:
https://juaml.github.io/junifer/main/using/queueing.html i.e. "alternatively is using venv use this yaml:"
_No response_
=> [DOC]: venv example

.github/workflows/ci.yml, docs/changes/newsfragments/318.misc, junifer/api/tests/test_api_utils.py, junifer/markers/brainprint.py, junifer/markers/falff/_afni_falff.py, junifer/markers/reho/_afni_reho.py, junifer/pipeline/pipeline_step_mixin.py, junifer/preprocess/smoothing/_afni_smoothing.py, junifer/utils/logging.py, pyproject.toml
The CI is acting up due to AFNI tests failing (ReHo and (f)ALFF) and FSL not being installed correctly. Although the latter is being avoided now, the former is not and thus coverage is not being reported. We need to come up with a flexible solution to handle situations like this.
=> [CI]: Improve CI

examples/run_compute_parcel_mean.py, examples/run_ets_rss_marker.py, examples/run_junifer_julearn.py, junifer/markers/functional_connectivity/crossparcellation_functional_connectivity.py
=> [CI]: Fix examples

docs/changes/newsfragments/356.bugfix, junifer/markers/brainprint.py
This PR fixes a bug in the `mri_binarize` command preparation for structures with multiple indices in `BrainPrint`.
=> [FIX]: Correct command for `mri_binarize` in `BrainPrint`

docs/changes/newsfragments/357.enh, junifer/utils/helpers.py
This PR sets proper stdout encoding for `run_ext_cmd` so that the output is easily human readable.
=> [ENH]: Set proper stdout encoding for `run_ext_cmd`

docs/api/onthefly.rst, docs/changes/newsfragments/354.feature, junifer/onthefly/__init__.py, junifer/onthefly/_brainprint.py
This PR adds a new module to the `onthefly` sub-package for downstream analyses of `BrainPrint` features. It has two functions as of now; one for `normalize` and other for `reweight`.
=> [ENH]: Add `brainprint` onthefly functions

docs/changes/newsfragments/360.bugfix, junifer/preprocess/confounds/fmriprep_confound_remover.py
This PR fixes the `spike` mapping from `adhoc` to `fmriprep`'s `"framewise_displacement"` by including it in the validation.
=> [FIX]: Enable `spike` for `fMRIPrepConfoundRemover`

docs/changes/newsfragments/367.enh, docs/extending/extension.rst, junifer/cli/parser.py
I am currently working on an extension in juni-farm which requires another .py file to be imported. When I add it to the `with` section of the yaml, even though both files are in there, it fails with a `ModuleNotFoundError`.
We originally though of having extensions be a single file, but now things have grown and it's not suitable anymore.
For example, in `my_extension_b.py`, we can have something like 
```python
from my_extension_a import CoolDataGrabber
@registerdatagrabber
class SuperCoolDataGrabber(CoolDataGrabber):
...
```
The solution is quite simple, for this to work, we need to add the path of each module to `sys.path`, so all imports work properly.
This creates an issue with the YAML file in the case of the `queue` command being inconsistent with the `run` one. 
On the `run` …
=> [ENH]: Allow for external modules to import other files

docs/changes/newsfragments/369.bugfix, junifer/pipeline/registry.py
This PR fixes a typo which didn't allow `fMRIPrepConfoundRemover` to be registered in `junifer.pipeline.registry`.
=> [BUG]: Typo for `fMRIPrepConfoundRemover` pipeline registration

docs/changes/newsfragments/370.bugfix, docs/whats_new.rst, junifer/datagrabber/aomic/piop2.py
=> Add `emomatching` task to AOMIC PIOP2 datagrabber

.github/workflows/ci-docs.yml, .github/workflows/ci.yml, .github/workflows/docs-preview.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/pypi.yml, docs/changes/newsfragments/372.misc, pyproject.toml, tox.ini
This PR drops support for Python 3.8 and adds support for Python 3.12. It also moves the coverage reporting to Python 3.12 and updates dependencies as required.
=> [MAINT]: Drop Python 3.8 and support Python 3.13

docs/changes/newsfragments/368.enh, junifer/data/template_spaces.py
This PR replaces the use of bulky human-template-xfm repo https://gin.g-node.org/juaml/human-template-xfms on Gin with a datalad-enabled one https://github.com/juaml/human-template-xfms on GitHub while still retaining the data hosting on Gin. This should speed-up file fetching and leverage the fantastic `git-annex`.
=> [ENH]: Use datalad human-template-xfms dataset for `junifer.data.get_xfm()`

docs/changes/newsfragments/391.misc, junifer/conftest.py, junifer/data/coordinates/_coordinates.py, junifer/data/masks/_masks.py, junifer/data/parcellations/_parcellations.py, junifer/data/pipeline_data_registry_base.py, junifer/datagrabber/hcp1200/tests/test_hcp1200.py, junifer/markers/falff/_afni_falff.py, junifer/markers/falff/_junifer_falff.py, junifer/markers/reho/_afni_reho.py, junifer/markers/reho/_junifer_reho.py, junifer/pipeline/pipeline_component_registry.py, junifer/pipeline/workdir_manager.py, junifer/utils/singleton.py
Refactor the Singleton so it stays a metaclass, allowing to reset the instances. 
This is needed if we want to test some elements independently and "reset" them between unit tests. E.g. the `WorkDirManager`
=> [ENH]: Refactor `Singleton` as a metaclass

docs/changes/newsfragments/389.enh, junifer/pipeline/tests/test_workdir_manager.py, junifer/pipeline/workdir_manager.py
This PR adds a `cleanup` parameter to the `WorkDirManager`, which allows to disable cleaning up temporary directories. While this does not add any important feature to the user, it allows to keep temporary files in case developers want to trace potential issues, mosly when using external tools.
=> Bypass cleanup of temporary dirs if needed

docs/changes/newsfragments/388.bugfix, junifer/data/coordinates/_ants_coordinates_warper.py, junifer/data/coordinates/_coordinates.py
When computing any marker on coordinates in native space, the coordinates in native space do not match the corresponding landmark in MNI space.
These are two examples in which the left (MNI space) do not match the right (T1w space).
In this first example, the coordinates are off-brain:
In this second example, the coordinates are in the brain, but not in the same landmark:
I expect that the coordinates point to the right landmark.
1. With latest junifer (main branch)
2. Modify the `WorkdirManager` code so that temporary directories are not cleaned.
3. Compute (f)ALFF on Aomic's `sub-0001` using `"Power2011"` using this script:
```
import pickle
from junifer.datagrabber.aomic import DataladAOMICID1000
from junifer.utils import configure_logging
from junifer.pipeline import WorkDirManager …
```
=> [BUG]: Coordinates transforms to native space using `ANTs` are off

docs/changes/newsfragments/398.bugfix, junifer/datagrabber/multiple.py, junifer/datagrabber/pattern.py, junifer/datagrabber/pattern_validation_mixin.py, junifer/datagrabber/tests/test_datalad_base.py, junifer/datagrabber/tests/test_multiple.py, junifer/datagrabber/tests/test_pattern_datalad.py, junifer/typing/__init__.pyi, junifer/typing/_typing.py, tools/create_bids_example_dataset.py, tools/create_bids_example_dataset_sessions.py
This PR fixes metadata update for `MultipleDataGrabber` and refactors `PatternDataGrabber.get_elements()` to check list-like data type values.
=> [BUG]: Fix metadata update for `MultipleDataGrabber`

docs/changes/newsfragments/401.feature, junifer/api/decorators.py, junifer/api/functions.py, junifer/cli/cli.py, junifer/cli/parser.py, junifer/data/_dispatch.py, junifer/data/masks/_masks.py, junifer/data/template_spaces.py, junifer/stats.py, junifer/storage/utils.py, junifer/testing/datagrabbers.py, junifer/typing/__init__.pyi, junifer/typing/_typing.py, junifer/utils/__init__.pyi, junifer/utils/_config.py, junifer/utils/config.py, junifer/utils/helpers.py, junifer/utils/logging.py, junifer/utils/singleton.py, junifer/utils/tests/test_config.py
The idea of this PR is to provide two functions `junifer.utils.config.get` and `junifer.utils.config.set` which can be retrieved at any moment, allowing for run-wide configuration options that can be set to control internal behaviour of junifer.
On intialization, the enviroment variables that start with `JUNIFER_` will also be set.
E.g.:
In order to test/debug, we might already have a dataset cloned with some files already present. Currently, junifer will try to check if the dataset id matches with the URL and if also if the dataset is dirty.
By setting `datagrabber.skipdirtycheck` and `datagrabber.skipidcheck`, we can avoid cloning and checking, which are long operations on big datasets.
=> [ENH]: Introduce `ConfigManager`

docs/changes/newsfragments/403.enh, docs/conf.py, junifer/datagrabber/datalad_base.py, junifer/datagrabber/tests/test_datalad_base.py
This PR uses the config module (#401) to implement a method for skipping checking the dataset ID and dirty status from datalad datasets that are already installed.
Checking the ID requires cloning into a temporary directory. Checking dirty status requires a call to datalad status.
These operations are time conusming.
This PR requires merging #401 first.
=> [ENH]: Use `junifer.utils.config` to skip dataset id and dirty checks (time consuming)

docs/changes/newsfragments/402.change, docs/changes/newsfragments/402.enh, junifer/api/functions.py, junifer/api/tests/test_functions.py, junifer/cli/cli.py, junifer/cli/parser.py, junifer/pipeline/workdir_manager.py
This PR allows `workdir` to be a mapping with `path` and `cleanup` keys in the YAML, which are then forwarded with checks to initialize `WorkDirManager` for debug cases with single element.
=> [ENH]: Allow `workdir` to forward parameters from YAML

docs/changes/newsfragments/407.feature, junifer/data/coordinates/_fsl_coordinates_warper.py, junifer/data/masks/_ants_mask_warper.py, junifer/data/masks/_fsl_mask_warper.py, junifer/data/parcellations/_ants_parcellation_warper.py, junifer/data/parcellations/_fsl_parcellation_warper.py, junifer/datagrabber/pattern_validation_mixin.py, junifer/preprocess/warping/_ants_warper.py, junifer/preprocess/warping/_fsl_warper.py
This PR introduces `reference` as a nested type of `BOLD` allowing to be specified either as part of a DataGrabber's `patterns` or added via `SpaceWarper`.
=> [ENH]: Introduce `BOLD.reference` nested data type

docs/changes/newsfragments/385.bugfix, junifer/pipeline/utils.py
There's a warning that some external commands are not available (e.g. ANTs' `ResampleImage`) but in the end it works.
I would expect the warning to not be there.
1. In juseless, run any yaml
```markdown
junifer:
version: 0.0.6.dev176
python:
version: 3.12.6
dependencies:
click: 8.1.7
numpy: 1.26.4
scipy: 1.14.1
datalad: 1.1.3
pandas: 2.2.2
nibabel: 5.2.1
ruamel.yaml: 0.17.40
looseversion: None
system:
platform: Linux-6.6.13+bpo-amd64-x86_64-with-glibc2.36
environment:
PATH:
/data/group/appliedml/tools/ants_2.5.0/binaries:/home/fraimondo/miniconda3/envs/junifer/bin:/home/fraimondo/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/games
```
```shell
2024-10-24 10:35:45,780 [ WARNING] /home/fraimondo/miniconda3/envs/junifer/lib/python3.12/site-packages/junifer/pipe …
```
=> [BUG]: External dependencies not found despite being there

docs/changes/newsfragments/408.enh, docs/changes/newsfragments/408.feature, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/smoothing/_afni_smoothing.py, junifer/preprocess/smoothing/_fsl_smoothing.py, junifer/preprocess/smoothing/_nilearn_smoothing.py, junifer/preprocess/smoothing/smoothing.py, junifer/preprocess/warping/_ants_warper.py, junifer/preprocess/warping/_fsl_warper.py
This PR refactors Preprocessors to sync data and their paths so that the results are idempotent. This also adds support for warping masks, if present, in `SpaceWarper`.
=> [ENH]: Refactor Preprocessors to sync data and their paths

docs/changes/newsfragments/404.change, docs/changes/newsfragments/404.enh, junifer/data/masks/_masks.py
=> [ENH]: Enable `compute_brain_mask` to use subject-specific probseg files

docs/changes/newsfragments/411.change, docs/changes/newsfragments/411.enh, junifer/data/parcellations/_parcellations.py, junifer/data/parcellations/tests/test_parcellations.py, junifer/markers/reho/tests/test_reho_parcels.py
This PR refactors the space transformation logic of parcellations to optimize warping at higher resolutions and joining in correct space. Follows very similar thought-process as in #395.
=> [ENH]: Rework parcellation logic

docs/changes/newsfragments/414.misc, junifer/data/masks/_masks.py, junifer/data/parcellations/_parcellations.py, junifer/markers/reho/tests/test_reho_parcels.py
This PR simplifies space warping for parcellations and masks.
=> [ENH]: Simplify space warping for parcellations and masks

docs/changes/newsfragments/319.enh, junifer/api/functions.py, junifer/api/queue_context/gnu_parallel_local_adapter.py, junifer/api/queue_context/htcondor_adapter.py, junifer/api/tests/test_functions.py, junifer/cli/parser.py, junifer/datagrabber/base.py, junifer/datagrabber/datalad_base.py, junifer/datagrabber/pattern.py, junifer/typing/__init__.pyi, junifer/typing/_typing.py
I just did this:
```
patterns:
VBM_GM: 
pattern: derivatives/fmriprep/sub-{subject}/anat/sub-{subject}_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
space: MNI152NLin2009cAsym
replacements: 
- subject
```
and then tried to run junifer with `--element sub-0001`. 
The issue (which take me a lot of time to solve) is that `sub-0001` is not in the _elements_ list, since the replacement is without the `sub-` prefix.
Now, there was no issue/warning from the run function. It cloned the dataset, did nothing and dropped the dataset.
We should implement a check in which if some of the elements in the list is not selected by the filter, there's a warning/error.
Exactly here is where we pass through the filter.
https://github.com/juaml/junifer/blob/a9e799caa3433d3d4eaa633d4565771b8eb297f6/junifer/a …
=> [ENH]: Raise/warn if element is not ran

docs/changes/newsfragments/420.bugfix, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py
This PR fixes `t_r` tampering done by `nilearn.image.clean_img` in `fMRIPrepConfoundRemover`.
=> [BUG]: `fMRIPrepConfoundRemover` sets incorrect `t_r` due to `nilearn.image.clean_img`

.github/workflows/ci-docs.yml, .github/workflows/ci.yml, docs/changes/newsfragments/424.misc, tox.ini
=> FIx CI coverage

junifer/cli/tests/test_cli_utils.py, junifer/data/coordinates/_coordinates.py, junifer/data/masks/_masks.py, junifer/data/masks/tests/test_masks.py, junifer/data/parcellations/_parcellations.py, junifer/data/parcellations/tests/test_parcellations.py, junifer/data/template_spaces.py, junifer/data/utils.py, junifer/typing/_typing.py, pyproject.toml
Currently, Junifer is handling the data, downloading from various sources. Ideally, this should be centralized and versiones.
1. Junifer uses the `junifer-data` API.
2. `junifer-data` keeps a datalad dataset with all data objects, including externals. Each commit to this datasets has a tag.
3. `junifer` knows exactly which is the tag that we are dealing with, so each junifer version will always work with the same data files.
4. We have a command `download` or similar that makes junifer download all (or the requested) files to be used later on with the `run` command.
_No response_
_No response_
=> [ENH]: Move data downloading/handling to `junifer-data` package.

docs/changes/newsfragments/421.change, docs/changes/newsfragments/421.enh, junifer/external/nilearn/tests/test_junifer_connectivity_measure.py, junifer/preprocess/confounds/fmriprep_confound_remover.py, junifer/preprocess/confounds/tests/test_fmriprep_confound_remover.py
This PR adds scrubbing support in `fMRIPrepConfoundRemover` by using `std_dvars` from fMRIPrep output.
=> [ENH]: Add scrubbing support in `fMRIPrepConfoundRemover`

Dockerfile-ci, Dockerfile-docs, docs/changes/newsfragments/427.misc
This PR removes `xfms` and adds `junifer-data` for CI images.
=> [CI]: Adapt usage of `junifer-data` for Docker images

docs/changes/newsfragments/431.bugfix, junifer/data/coordinates/_coordinates.py
When trying to fetch Power2011 coordinates, I get a datalad error:
```
RuntimeError: Failed to get file from dataset: [{'action': 'get', 'path': '/home/fraimondo/junifer_data/v1/coordinates/Power2011/Power2011_MNI_VOIs.txt', 'status': 'impossible', 'refds': '/home/fraimondo/junifer_data/v1', 'message': 'path does not exist'}]
```
Indeed it seems that the issue comes from the name:
https://github.com/juaml/junifer/blob/1b2072ef4e6c08d1f84ea4f1ddc5aee079d3d84e/junifer/data/coordinates/_coordinates.py#L279-L281
It expects Power2011 as the `name`, but junifer-data has it as Power only.
I expect the Power 2011 coordinates to be loaded.
1. With junifer main branch.
2. Run
``` Python
from junifer.data import get_data
get_data("coordinates", "Power2011", target_data=None)
```
```markdown
junifer: …
```
=> [BUG]: Cannot fetch Power2011 coordinates

docs/changes/newsfragments/434.enh, junifer/data/coordinates/_coordinates.py, junifer/data/masks/_masks.py, junifer/data/parcellations/_parcellations.py, junifer/data/template_spaces.py, junifer/data/utils.py, pyproject.toml
This PR will implement a hexsha check using junifer data.
This way, if the expected version and hexsha pair do not match in junifer data, an error will be raised.
It might look like an overkill, but junifer-data is now a key component that will definitely affect the computation if modified.
=> Use hexsha to verify junifer-data integrity

docs/builtin.rst, docs/changes/newsfragments/436.bugfix, junifer/data/coordinates/_coordinates.py
`Power2011_MNI_VOIs.txt` and `Power2013_MNI_VOIs.tsv` contain the same coordinates with different ROI numbers. This creates the illusion that they are different when they are not and leads to dissimilarities, e.g. when computing FC, simply because of the ROI ordering.
I would suggest deleting the `Power2013_MNI_VOIs.tsv`, since Power et al., 2013 did not introduce new coordinates but reused the ones from Power et al. (2011) with unmatching ROI numbering.
**From Method section of Power et al. (2013)**
> **Node Definitions** 
> For the areal network, a collection of 264 ROIs defined in Power et al. (2011) were used as network nodes [...]
=> Power2011 and Power2013 files contain the same coordinates with mismatched ROI numbering

Dockerfile-ci, Dockerfile-docs, docs/changes/newsfragments/438.misc
This PR bumps `junifer-data` to v2 for building Docker images.
=> [CI]: Bump `junifer-data` to v2 for building Docker images

.github/workflows/ci.yml, .github/workflows/docs-preview.yml, .github/workflows/docs.yml, docs/builtin.rst, docs/changes/newsfragments/437.misc, junifer/data/coordinates/_coordinates.py, junifer/data/utils.py
This PR bumps `junifer-data` to v2. Removes `Power` and adds `Seitzman2018` to `CoordinatesRegistry`.
=> [MAINT]: Bump `junifer-data` version to v2

docs/changes/newsfragments/333.enh, junifer/external/nilearn/junifer_connectivity_measure.py, junifer/external/nilearn/tests/test_junifer_connectivity_measure.py, junifer/markers/functional_connectivity/functional_connectivity_base.py
Adapt https://github.com/czbiohub-sf/xicor to be used as a correlation metric for functional connectivity markers.
As an option for nilearn's ConnectivityMeasure.
```shell
https://github.com/czbiohub-sf/xicor
```
_No response_
=> [ENH]: Support "xi" correlation metric for functional connectivity

docs/changes/newsfragments/444.bugfix, junifer/storage/hdf5.py, junifer/storage/tests/test_hdf5.py
=> [BUG]: Add `timeseries_2d` as valid input type for `HDF5FeatureStorage`

docs/builtin.rst, docs/changes/newsfragments/443.feature, junifer/pipeline/pipeline_component_registry.py, junifer/preprocess/__init__.pyi, junifer/preprocess/_temporal_slicer.py, junifer/preprocess/tests/test_temporal_slicer.py
To have the option to define which segment of the time series to use for extracting connectomes (define start and end point). For example, cut a 20-minute sequence after 10 minutes and extract connectomes from only the second part. 
Use-Case: We have a 24 minute sequence with a task and a control task performed sequentially and want to analyze them separately. 
Cut the time series before calculating the connectomes.
```shell
```
@kaurao
=> [ENH]: Add `TemporalSlicer`

docs/changes/newsfragments/450.doc, docs/changes/newsfragments/450.feature, docs/extending/data_registries.rst, docs/extending/extension.rst, docs/extending/index.rst, junifer/api/decorators.py, junifer/api/tests/test_decorators.py, junifer/data/__init__.pyi, junifer/data/_dispatch.py, junifer/data/coordinates/_coordinates.py, junifer/data/masks/_masks.py, junifer/data/parcellations/_parcellations.py, junifer/data/parcellations/tests/test_parcellations.py, junifer/data/tests/test_dispatch.py, junifer/typing/__init__.pyi, junifer/typing/_typing.py
This PR adds support for extending data registries with custom ones. Custom data registries can be interacted via `*_data` functions just like in-built ones.
=> [ENH]: Enable extendable data registries

conda-env.yml, docs/builtin.rst, docs/changes/newsfragments/458.change, docs/changes/newsfragments/458.feature, docs/changes/newsfragments/458.misc, docs/extending/index.rst, docs/extending/maps.rst, junifer/data/__init__.pyi, junifer/data/_dispatch.py, junifer/data/maps/__init__.py, junifer/data/maps/__init__.pyi, junifer/data/maps/_ants_maps_warper.py, junifer/data/maps/_fsl_maps_warper.py, junifer/data/maps/_maps.py, junifer/data/maps/tests/test_maps.py, junifer/data/masks/_masks.py, junifer/data/parcellations/_parcellations.py, pyproject.toml
This PR introduces `MapsRegistry` for centralized management of maps (probabilistic atlas / parcellations).
=> [ENH]: Introduce `MapsRegistry`

docs/changes/newsfragments/454.bugfix, junifer/pipeline/utils.py
This PR fixes FSL presence checking status codes.
=> Fix check for FSL

Dockerfile-ci, Dockerfile-docs, docs/changes/newsfragments/465.misc
This PR bumps `junifer-data` to v4 for building Docker images.
=> [CI]: Bump `junifer-data` to v4 for building Docker images

Dockerfile-ci, docs/changes/newsfragments/467.misc
This PR disabled FSL installation for junifer-ci build as standard GitHub Runner runs out of space.
=> [CI]: Disable FSL installation for junifer-ci Docker image

docs/changes/newsfragments/257.change, docs/changes/newsfragments/257.enh, junifer/data/_dispatch.py, junifer/data/parcellations/_parcellations.py, junifer/data/parcellations/tests/test_parcellations.py, junifer/markers/parcel_aggregation.py, junifer/markers/tests/test_parcel_aggregation.py
I want to _register_ the Glasser parcellation: https://afni.nimh.nih.gov/pub/dist/atlases/MNI_HCP/MNI_Glasser_HCP_2021_v1.0a/
However, I get this error:
```
File "/home/fraimondo/dev/tbox/junifer/junifer/data/parcellations.py", line 269, in load_parcellation
raise_error(
File "/home/fraimondo/dev/tbox/junifer/junifer/utils/logging.py", line 289, in raise_error
raise klass(msg)
ValueError: Parcellation Glasser must have all the values in the range  [0, 361].
```
This is because so far, junifer expects that parcellation values are continuous. Some parcellations are not, like this one. The values are 1-180 for one hemisphere, and 1001-1180 for the other.
This was a restriction added when merging parcellations, as we have to "shift" the values to merge them, and this is done by adding the …
=> [BUG]: Cannot register parcellation with non-continuous values
